'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowUp, Bell, Check, MessageCircle, Search, UserRound, Bot, X, ArrowLeft, ArrowRight, RefreshCw } from 'lucide-react';
import type { ChatConversation, ChatSnapshot } from '@/lib/chat-types';
import { ChatRequestError, chatRequest, startChatPolling } from '@/lib/chat-client';
const labels = { bot: 'Assistant active', waiting: 'Wants a person', human: 'Team conversation', closed: 'Resolved' };
export function ConversationInbox({ userId }: { userId: number }) {
  const [rows, setRows] = useState<ChatConversation[]>([]), [filter, setFilter] = useState('all'), [search, setSearch] = useState(''), [page, setPage] = useState(1), [next, setNext] = useState(false), [total, setTotal] = useState(0), [attention, setAttention] = useState(0), [selected, setSelected] = useState<number | null>(null), [chat, setChat] = useState<ChatSnapshot | null>(null), [input, setInput] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notifications, setNotifications] = useState(false), [notice, setNotice] = useState<ChatConversation | null>(null), [database, setDatabase] = useState<'local'|'shared'|null>(null), [lastSync, setLastSync] = useState(''), [query, setQuery] = useState('');
  const seen = useRef(new Set<string>()), listVersion = useRef(0), detailVersion = useRef(0), log = useRef<HTMLDivElement>(null), lock = useRef(false), pending = useRef<{ id:number; text:string; key:string } | null>(null), listBusy = useRef(false), detailBusy = useRef(false);
  const forgetPrivateData = useCallback((cause:unknown) => { if(cause instanceof ChatRequestError && [401,403].includes(cause.status)){listVersion.current++;detailVersion.current++;setRows([]);setChat(null);setSelected(null);setNotice(null);setInput('');setAttention(0);setTotal(0);setLastSync('');pending.current=null;seen.current.clear();setError('Sign in to the dashboard again.');} },[]);
  const refresh = useCallback(async () => {
    if(listBusy.current)return; listBusy.current=true; const version = ++listVersion.current;
    try { const data = await chatRequest(`/api/chat/admin?filter=${filter}&search=${encodeURIComponent(query)}&page=${page}`); if(version!==listVersion.current)return; setError(''); setRows(data.conversations); setTotal(data.total); setNext(data.hasNextPage); setAttention(data.attention); setDatabase(data.storage); setLastSync(new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'}));
      for(const row of data.alerts as ChatConversation[]) if(row.needsAttention) {const key=`${row.id}:${row.lastMessageAt}`; if(!seen.current.has(key)) { seen.current.add(key); setNotice(row); if(notifications && Notification.permission==='granted')new Notification('High4Tech · Studio support',{body:`${row.visitorName}: ${row.status==='waiting'?'Asked to speak with the team':row.preview || 'New message'}`,tag:`h4t-chat-${row.id}`}); }}
    } catch(cause) { if(version===listVersion.current)setError(cause instanceof Error?cause.message:'The inbox couldn’t connect.'); forgetPrivateData(cause); }
    finally {listBusy.current=false;}
  }, [filter, query, page, notifications, forgetPrivateData]);
  const refreshChat = useCallback(async () => {
    if(!selected || lock.current || detailBusy.current)return; detailBusy.current=true; const version=++detailVersion.current;
    try {const data=await chatRequest(`/api/chat/admin?id=${selected}`);if(version!==detailVersion.current)return;setError('');setChat(current=>current?.conversation?.id===selected?{...data,hasOlder:current.messages[0]?.id<data.messages[0]?.id?current.hasOlder:data.hasOlder,messages:[...new Map([...current.messages,...data.messages].map(message=>[message.id,message])).values()].sort((a,b)=>a.id-b.id)}:data);}catch(cause){if(version===detailVersion.current)setError(cause instanceof Error?cause.message:'Messages couldn’t load.'); forgetPrivateData(cause);}
    finally {detailBusy.current=false;}
  },[selected,forgetPrivateData]);
  useEffect(()=>{const timer=setTimeout(()=>{setQuery(search);setPage(1);},300);return()=>clearTimeout(timer);},[search]);
  useEffect(()=>{const stop=startChatPolling(refresh,2500);return()=>{stop();listVersion.current++;};},[refresh]);
  useEffect(()=>{setChat(null);setInput('');pending.current=null;const stop=startChatPolling(refreshChat,2000);return()=>{stop();detailVersion.current++;};},[refreshChat]);
  useEffect(()=>{log.current?.scrollTo({top:log.current.scrollHeight,behavior:'smooth'});},[chat?.messages.at(-1)?.id]);
  const choose=(id:number)=>{detailVersion.current++;setSelected(id);setError('');};
  async function action(value:string){if(!selected||lock.current)return;lock.current=true;setBusy(true);setError('');const id=selected,text=input.trim(),key=value==='reply'&&pending.current?.id===id&&pending.current.text===text?pending.current.key:crypto.randomUUID();if(value==='reply')pending.current={id,text,key};detailVersion.current++;
    try{const data=await chatRequest('/api/chat/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,action:value,message:text,requestId:key})});setChat(current=>({...data,messages:[...new Map([...(current?.conversation?.id===id?current.messages:[]),...data.messages].map(message=>[message.id,message])).values()].sort((a,b)=>a.id-b.id)}));if(value==='reply'){setInput('');pending.current=null;}if(notice?.id===id)setNotice(null);void refresh();}catch(cause){setError(cause instanceof Error?cause.message:'Please try again.');forgetPrivateData(cause);}finally{setBusy(false);lock.current=false;}}
  async function older(){if(!selected||!chat?.messages.length)return;try{const data=await chatRequest(`/api/chat/admin?id=${selected}&before=${chat.messages[0].id}`);setChat(current=>current?.conversation?.id===selected?{...current,hasOlder:data.hasOlder,messages:[...data.messages,...current.messages]}:current);}catch(cause){setError('Earlier messages couldn’t load.');forgetPrivateData(cause);}}
  async function enableNotifications(){if(!('Notification' in window)){setError('This browser doesn’t support notifications. Inbox alerts still work.');return;}const permission=await Notification.requestPermission();setNotifications(permission==='granted');if(permission!=='granted')setError('Browser notifications are off. Inbox alerts still work.');}
  const row=chat?.conversation, mine=row?.assignedTo===userId, other=Boolean(row?.assignedTo&&!mine);
  return <section className="support-workspace"><header className="support-heading"><div><span className="h4t-admin-eyebrow">HIGH4TECH / CONVERSATIONS</span><h2>A little closer to your customers.</h2><p>Saved messages, published answers, and a person when it matters.</p></div><button className="h4t-admin-button secondary" onClick={()=>void enableNotifications()} disabled={notifications}><Bell size={16}/>{notifications?'Alerts enabled':'Enable browser alerts'}<span className="support-attention">{attention}</span></button></header>
    <div className="support-connection" role="status"><span><i className={error?'disconnected':''}/>{lastSync ? `Inbox checked ${lastSync}` : 'Connecting to inbox…'}</span><button onClick={()=>{void refresh();void refreshChat();}}><RefreshCw size={13}/>Refresh</button></div>
    {database==='local' && <div className="support-database-note"><strong>Inbox connected to this server</strong><p>Chats and project briefs sent through this website appear here. Separate copies of the website need the same database to share conversations.</p></div>}
    {notice && <div className="support-notification" role="status"><Bell size={17}/><span><b>{notice.visitorName}</b> · {notice.status==='waiting'?'Would like to speak to a person':'Has a new message for the team'}</span><button onClick={()=>choose(notice.id)}>View conversation<ArrowRight size={15}/></button><button aria-label="Dismiss inbox notification" onClick={()=>setNotice(null)}><X size={15}/></button></div>}
    {error && <p className="support-error" role="alert">{error}<button onClick={()=>{setError('');void refresh();void refreshChat();}}>Retry</button></p>}
    <div className={`support-desk ${row?'has-selection':''}`}><aside className="support-list"><div className="support-list-tools"><label><Search size={16}/><input aria-label="Search conversations" placeholder="Find a visitor or message" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></label><select aria-label="Filter conversations" value={filter} onChange={e=>{setFilter(e.target.value);setPage(1);}}><option value="all">All conversations</option><option value="attention">Needs attention</option><option value="waiting">Human requests</option><option value="human">Team conversations</option><option value="bot">Assistant conversations</option><option value="closed">Resolved</option></select></div><div className="support-visitors">{rows.map(visitor=><button key={visitor.id} disabled={busy} className={selected===visitor.id?'is-selected':''} onClick={()=>choose(visitor.id)}><span className="support-initial">{visitor.visitorName.slice(0,2).toUpperCase()}</span><span><strong>{visitor.visitorName}{visitor.needsAttention&&<i/>}</strong><small>{visitor.preview || 'Conversation started'}</small><span className={`support-status ${visitor.status}`}>{labels[visitor.status]}</span></span><time>{new Date(visitor.lastMessageAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time></button>)}{!rows.length&&<p className="support-empty-list">{search || filter!=='all'?'No conversations match this filter.':'Your first visitor conversation will appear here.'}</p>}</div><footer><button aria-label="Previous conversations" disabled={page===1} onClick={()=>setPage(page-1)}><ArrowLeft size={14}/></button><span>{total} conversations · Page {page}</span><button aria-label="Next conversations" disabled={!next} onClick={()=>setPage(page+1)}><ArrowRight size={14}/></button></footer></aside>
    <div className="support-chat">{row?<><header><div><strong>{row.visitorName}</strong><span className={`support-status ${row.status}`}>{labels[row.status]}</span></div><small>{row.status==='human'?(mine?'You’re replying · Assistant paused':'Another team member is replying'):row.status==='waiting'?'The visitor asked for the team':'Conversation history'}</small></header><div className="support-transcript" ref={log}>{chat.hasOlder&&<button className="support-load" onClick={()=>void older()}>Earlier messages</button>}{chat.messages.map(message=><div key={message.id} className={`support-message ${message.role}`}><span>{message.role==='visitor'?row.visitorName:message.role==='staff'?message.staffName:'High4Tech '+(message.role==='assistant'?'assistant':'studio')}<time>{new Date(message.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time></span><p>{message.body}</p>{message.reply?.resources?.map(resource=><a key={resource.id} href={`/tools-and-resources/${resource.id}`} target="_blank" rel="noopener noreferrer">{resource.title} ↗</a>)}</div>)}</div><form className="support-compose" onSubmit={e=>{e.preventDefault();if(input.trim())void action('reply');}}><textarea aria-label="Reply to visitor" placeholder={row.status==='human'&&mine?'Reply as the studio team…':'Take over to write a reply'} value={input} onChange={e=>setInput(e.target.value)} maxLength={500} disabled={!mine||row.status!=='human'||busy}/><button aria-label="Send staff reply" disabled={!input.trim()||!mine||row.status!=='human'||busy}><ArrowUp size={18}/></button></form></>:<div className="support-select"><MessageCircle size={38}/><h3>Every conversation, in one place.</h3><p>Select a visitor to read their messages or take over from the assistant.</p></div>}</div>
    <aside className="support-profile"><h3><UserRound size={17}/>Visitor details</h3>{row?<><div className="support-profile-avatar">{row.visitorName.slice(0,2).toUpperCase()}</div><h4>{row.visitorName}</h4><dl><dt>Contact email</dt><dd>{row.visitorEmail ? <a href={`mailto:${row.visitorEmail}`}>{row.visitorEmail}</a> : 'Not shared'}</dd><dt>Phone number</dt><dd>{row.visitorPhone ? <a href={`tel:${row.visitorPhone}`}>{row.visitorPhone}</a> : 'Not shared'}</dd><dt>Source</dt><dd>{row.channel==='inquiry'?'Mail · Project brief':'Messages'}</dd><dt>Status</dt><dd>{labels[row.status]}</dd><dt>Last activity</dt><dd>{new Date(row.lastMessageAt).toLocaleString()}</dd><dt>Chat assignment</dt><dd>{other?'Another team member':mine?'Assigned to you':'Unassigned'}</dd></dl><div className="support-actions"><button className="h4t-admin-button" disabled={busy||other||row.status==='closed'||mine&&row.status==='human'} onClick={()=>void action('claim')}><UserRound size={16}/>{mine?'You’re connected':'Jump in · Take over'}</button><button className="h4t-admin-button secondary" disabled={busy||other||!['human','waiting'].includes(row.status)} onClick={()=>void action('bot')}><Bot size={16}/>Return to assistant</button><button className="h4t-admin-button secondary" disabled={busy||row.status==='closed'||other} onClick={()=>void action('close')}><Check size={16}/>Resolve conversation</button>{row.needsAttention&&<button className="support-mark-read" disabled={busy} onClick={()=>void action('seen')}>Mark notification as read</button>}</div><small>Contact details are provided by the visitor. Browser alerts work while this dashboard is open.</small></>:<p>Visitor details and handoff actions appear when you select a conversation.</p>}</aside></div>
  </section>;
}
