import type { ServerProps } from 'payload';
import { FileText, MessageCircle, SlidersHorizontal, ArrowUpRight, Globe, FolderOpen } from 'lucide-react';
import { AssistantTest } from './AssistantTest';
export async function StudioDashboard({ payload, user }: Pick<ServerProps, 'payload' | 'user'>) {
  if (!user) return null;
  const [answers, documents, drafts, projects, settings] = await Promise.all([
    payload.count({ collection: 'chatbot-data', where: { _status: { equals: 'published' } }, overrideAccess: false, user }),
    payload.count({ collection: 'knowledge-documents', where: { _status: { equals: 'published' } }, overrideAccess: false, user }),
    payload.countVersions({ collection: 'knowledge-documents', where: { and: [{ 'version._status': { equals: 'draft' } }, { latest: { equals: true } }] }, overrideAccess: false, user }),
    payload.count({ collection: 'projects', where: { _status: { equals: 'published' } }, overrideAccess: false, user }),
    payload.findGlobal({ slug: 'assistant-settings', overrideAccess: false, user }),
  ]);
  const name = user.name?.trim().split(' ')[0];
  const cards = [{ title: 'Approved answers', value: answers.totalDocs, text: 'Published Q&A for your visitors', href: '/admin/collections/chatbot-data', icon: MessageCircle }, { title: 'Knowledge documents', value: documents.totalDocs, text: `${drafts.totalDocs} draft${drafts.totalDocs === 1 ? '' : 's'} waiting for review`, href: '/admin/collections/knowledge-documents', icon: FileText }, { title: 'Published projects', value: projects.totalDocs, text: 'Your studio’s work, ready to explore', href: '/admin/collections/projects', icon: FolderOpen }];
  return <section className="h4t-dashboard"><header className="h4t-dashboard-header"><div><span className="h4t-admin-eyebrow">HIGH4TECH / STUDIO CONTROL</span><h1>{name ? `Welcome back, ${name}.` : 'Your studio. Your knowledge.'}</h1><p>Give the assistant the facts. Give your visitors the right next step.</p></div><a href="/" target="_blank" rel="noopener noreferrer" className="h4t-admin-button secondary"><Globe size={16}/>View studio<ArrowUpRight size={14}/></a></header><div className="h4t-dashboard-cards">{cards.map(card => <a key={card.title} href={card.href}><card.icon size={21}/><strong>{card.value}</strong><h3>{card.title}<ArrowUpRight size={14}/></h3><p>{card.text}</p></a>)}</div><div className="support-dashboard-link"><MessageCircle size={20}/><div><h2>Your conversations are here.</h2><p>Read saved chats, respond to human requests, and join a live conversation.</p></div><a className="h4t-admin-button" href="/admin/conversations">Open support inbox<ArrowUpRight size={15}/></a></div><div className="h4t-dashboard-knowledge"><div><span className={`h4t-live-badge ${settings.enabled === false ? 'paused' : ''}`}><i/>{settings.enabled === false ? 'Assistant paused' : 'Assistant ready'}</span><h2>Useful answers start here.</h2><p>Import your text or data file, review the extracted content, then publish. The assistant returns relevant passages with their source and declines unsupported questions.</p><div className="h4t-dashboard-actions"><a className="h4t-admin-button" href="/admin/collections/knowledge-documents/create"><FileText size={15}/>Import knowledge</a><a className="h4t-admin-button secondary" href="/admin/collections/chatbot-data/create"><MessageCircle size={15}/>Write an answer</a><a className="h4t-admin-text-link" href="/admin/globals/assistant-settings"><SlidersHorizontal size={14}/>Settings</a></div><ol><li><b>01</b><span>Add TXT, Markdown, CSV, or JSON. You can also write directly.</span></li><li><b>02</b><span>Review public facts. Save drafts while you prepare.</span></li><li><b>03</b><span>Publish and test. Changes reach the assistant immediately.</span></li></ol><small>No paid AI API. No external knowledge. Original files aren’t stored; reviewed text lives in your database.</small></div><AssistantTest/></div></section>;
}
