/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'chat-conversations': ChatConversation;
    'chat-messages': ChatMessage;
    'security-rate-limits': SecurityRateLimit;
    users: User;
    media: Media;
    services: Service;
    projects: Project;
    newsroom: Newsroom;
    resources: Resource;
    faqs: Faq;
    pricing: Pricing;
    'ai-services': AiService;
    'chatbot-data': ChatbotDatum;
    'knowledge-documents': KnowledgeDocument;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'chat-conversations': ChatConversationsSelect<false> | ChatConversationsSelect<true>;
    'chat-messages': ChatMessagesSelect<false> | ChatMessagesSelect<true>;
    'security-rate-limits': SecurityRateLimitsSelect<false> | SecurityRateLimitsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    newsroom: NewsroomSelect<false> | NewsroomSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    pricing: PricingSelect<false> | PricingSelect<true>;
    'ai-services': AiServicesSelect<false> | AiServicesSelect<true>;
    'chatbot-data': ChatbotDataSelect<false> | ChatbotDataSelect<true>;
    'knowledge-documents': KnowledgeDocumentsSelect<false> | KnowledgeDocumentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'assistant-settings': AssistantSetting;
    'site-settings': SiteSetting;
    'contact-info': ContactInfo;
  };
  globalsSelect: {
    'assistant-settings': AssistantSettingsSelect<false> | AssistantSettingsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'contact-info': ContactInfoSelect<false> | ContactInfoSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Use the live inbox on the dashboard to take over and reply.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-conversations".
 */
export interface ChatConversation {
  id: number;
  visitorKey: string;
  visitorName: string;
  visitorEmail?: string | null;
  visitorPhone?: string | null;
  channel?: ('chat' | 'inquiry') | null;
  status: 'bot' | 'waiting' | 'human' | 'closed';
  assignedTo?: (number | null) | User;
  needsAttention?: boolean | null;
  handoffAt?: string | null;
  lastMessageAt: string;
  preview?: string | null;
  lastVisitorAt?: string | null;
  lastInquiryAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-messages".
 */
export interface ChatMessage {
  id: number;
  conversation: number | ChatConversation;
  role: 'visitor' | 'assistant' | 'staff' | 'system';
  body: string;
  requestKey: string;
  staffName?: string | null;
  reply?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "security-rate-limits".
 */
export interface SecurityRateLimit {
  id: number;
  key: string;
  windowStart: number;
  count: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  short: string;
  description: string;
  /**
   * Add one item per row.
   */
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Add one item per row.
   */
  deliverables?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional project walkthroughs, service demos, or tool tutorials. Paste a YouTube URL, not embed HTML.
   */
  videos?:
    | {
        title?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  symbol?: ('flower' | 'orbit' | 'spark') | null;
  draft?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  name: string;
  slug: string;
  type: string;
  category: string;
  year: string;
  image?: (number | null) | Media;
  /**
   * Optional existing local image path. An uploaded image takes priority.
   */
  imagePath?: string | null;
  gallery?:
    | {
        image?: (number | null) | Media;
        /**
         * Optional existing local image path. An uploaded image takes priority.
         */
        imagePath?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  color?: string | null;
  description: string;
  intro: string;
  /**
   * Optional project walkthroughs, service demos, or tool tutorials. Paste a YouTube URL, not embed HTML.
   */
  videos?:
    | {
        title?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsroom".
 */
export interface Newsroom {
  id: number;
  title: string;
  slug: string;
  category: string;
  read: string;
  summary: string;
  paragraphs?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  artwork?: ('type' | 'orbit' | 'grid') | null;
  image?: (number | null) | Media;
  publishedAt?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  title: string;
  slug: string;
  description: string;
  category: string;
  /**
   * Select every platform this tool actually supports.
   */
  platforms: ('wordpress' | 'shopify' | 'android' | 'ios' | 'custom' | 'pos' | 'other')[];
  /**
   * Searchable purposes and synonyms, e.g. inventory, stock tracking, low-stock alerts. The assistant uses these with the description.
   */
  capabilities?: string | null;
  /**
   * Optional project walkthroughs, service demos, or tool tutorials. Paste a YouTube URL, not embed HTML.
   */
  videos?:
    | {
        title?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  price: 'Free' | 'Paid';
  label: string;
  /**
   * External platform for use or purchase.
   */
  url?: string | null;
  icon?: ('gradient' | 'liquid' | 'cube' | 'tool') | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing".
 */
export interface Pricing {
  id: number;
  title: string;
  price: string;
  unit: string;
  label: string;
  intro: string;
  /**
   * Add one item per row.
   */
  items?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  sample?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-services".
 */
export interface AiService {
  id: number;
  name: string;
  kind: 'workflow' | 'assistant' | 'integration';
  text: string;
  /**
   * Add one item per row.
   */
  items?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Published answers are available to visitors. Drafts and unpublished revisions stay private.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chatbot-data".
 */
export interface ChatbotDatum {
  id: number;
  question: string;
  /**
   * Comma-separated words or phrases, e.g. pricing, project cost. Avoid generic words such as “what”.
   */
  keywords: string;
  answer: string;
  link?: string | null;
  label?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Import a data file, review its text, then publish. The assistant quotes published passages only; raw documents are private.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-documents".
 */
export interface KnowledgeDocument {
  id: number;
  title: string;
  /**
   * Original filename for your reference. The file itself is not stored.
   */
  sourceName?: string | null;
  /**
   * This text is the source of answers. Remove confidential material before publishing.
   */
  content: string;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'chat-conversations';
        value: number | ChatConversation;
      } | null)
    | ({
        relationTo: 'chat-messages';
        value: number | ChatMessage;
      } | null)
    | ({
        relationTo: 'security-rate-limits';
        value: number | SecurityRateLimit;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'newsroom';
        value: number | Newsroom;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'pricing';
        value: number | Pricing;
      } | null)
    | ({
        relationTo: 'ai-services';
        value: number | AiService;
      } | null)
    | ({
        relationTo: 'chatbot-data';
        value: number | ChatbotDatum;
      } | null)
    | ({
        relationTo: 'knowledge-documents';
        value: number | KnowledgeDocument;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-conversations_select".
 */
export interface ChatConversationsSelect<T extends boolean = true> {
  visitorKey?: T;
  visitorName?: T;
  visitorEmail?: T;
  visitorPhone?: T;
  channel?: T;
  status?: T;
  assignedTo?: T;
  needsAttention?: T;
  handoffAt?: T;
  lastMessageAt?: T;
  preview?: T;
  lastVisitorAt?: T;
  lastInquiryAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-messages_select".
 */
export interface ChatMessagesSelect<T extends boolean = true> {
  conversation?: T;
  role?: T;
  body?: T;
  requestKey?: T;
  staffName?: T;
  reply?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "security-rate-limits_select".
 */
export interface SecurityRateLimitsSelect<T extends boolean = true> {
  key?: T;
  windowStart?: T;
  count?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  short?: T;
  description?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  deliverables?:
    | T
    | {
        value?: T;
        id?: T;
      };
  videos?:
    | T
    | {
        title?: T;
        url?: T;
        id?: T;
      };
  symbol?: T;
  draft?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  category?: T;
  year?: T;
  image?: T;
  imagePath?: T;
  gallery?:
    | T
    | {
        image?: T;
        imagePath?: T;
        alt?: T;
        id?: T;
      };
  color?: T;
  description?: T;
  intro?: T;
  videos?:
    | T
    | {
        title?: T;
        url?: T;
        id?: T;
      };
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsroom_select".
 */
export interface NewsroomSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  read?: T;
  summary?: T;
  paragraphs?:
    | T
    | {
        value?: T;
        id?: T;
      };
  artwork?: T;
  image?: T;
  publishedAt?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  category?: T;
  platforms?: T;
  capabilities?: T;
  videos?:
    | T
    | {
        title?: T;
        url?: T;
        id?: T;
      };
  price?: T;
  label?: T;
  url?: T;
  icon?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing_select".
 */
export interface PricingSelect<T extends boolean = true> {
  title?: T;
  price?: T;
  unit?: T;
  label?: T;
  intro?: T;
  items?:
    | T
    | {
        value?: T;
        id?: T;
      };
  sample?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-services_select".
 */
export interface AiServicesSelect<T extends boolean = true> {
  name?: T;
  kind?: T;
  text?: T;
  items?:
    | T
    | {
        value?: T;
        id?: T;
      };
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chatbot-data_select".
 */
export interface ChatbotDataSelect<T extends boolean = true> {
  question?: T;
  keywords?: T;
  answer?: T;
  link?: T;
  label?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-documents_select".
 */
export interface KnowledgeDocumentsSelect<T extends boolean = true> {
  title?: T;
  sourceName?: T;
  content?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assistant-settings".
 */
export interface AssistantSetting {
  id: number;
  enabled?: boolean | null;
  welcomeMessage: string;
  fallbackMessage: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  agencyName: string;
  studioName: string;
  logo?: (number | null) | Media;
  logoPath?: string | null;
  mark?: (number | null) | Media;
  markPath?: string | null;
  headline: string;
  introduction?: string | null;
  aboutTitle: string;
  aboutText?: string | null;
  contentSeeded?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info".
 */
export interface ContactInfo {
  id: number;
  email: string;
  calLink?: string | null;
  whatsapp?: string | null;
  instagram?: string | null;
  linkedin?: string | null;
  behance?: string | null;
  welcomeSubject: string;
  welcomeBody: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assistant-settings_select".
 */
export interface AssistantSettingsSelect<T extends boolean = true> {
  enabled?: T;
  welcomeMessage?: T;
  fallbackMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  agencyName?: T;
  studioName?: T;
  logo?: T;
  logoPath?: T;
  mark?: T;
  markPath?: T;
  headline?: T;
  introduction?: T;
  aboutTitle?: T;
  aboutText?: T;
  contentSeeded?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info_select".
 */
export interface ContactInfoSelect<T extends boolean = true> {
  email?: T;
  calLink?: T;
  whatsapp?: T;
  instagram?: T;
  linkedin?: T;
  behance?: T;
  welcomeSubject?: T;
  welcomeBody?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}