'use client';
import { playUiSound } from './sound';
import { useState, useEffect } from 'react';
import { ArrowUpRight, Check, Copy, Mail, ArrowLeft } from 'lucide-react';

export function ContactForm() {
  const [interest,setInterest] = useState('A new website');
  const [values,setValues] = useState({name:'',email:'',company:'',message:''});
  const [budget,setBudget] = useState('Let’s discuss');
  const [prepared,setPrepared] = useState(false);
  const [copied,setCopied] = useState(false);
  useEffect(() => {const value = new URLSearchParams(window.location.search).get('interest');if(value) setInterest(value);const saved=sessionStorage.getItem('h4t-call-preference');if(saved){try{const call=JSON.parse(saved);setInterest(call.topic);setValues(v=>({...v,message:`I’d like to arrange a discovery call about ${call.topic.toLowerCase()}.${call.date?` My preferred date is ${call.date}.`:''}`}));sessionStorage.removeItem('h4t-call-preference');}catch{}}},[]);
  const draft = `Hi High4Tech,\n\nMy name is ${values.name}${values.company ? ` from ${values.company}` : ''}.\nI’m interested in: ${interest}.\nBudget: ${budget}.\n\n${values.message}\n\nReply to: ${values.email}`;
  const mailto = `mailto:sales@high4tech.io?subject=${encodeURIComponent(`Project inquiry — ${values.name}`)}&body=${encodeURIComponent(draft)}`;
  async function copy() {try {await navigator.clipboard.writeText(draft);setCopied(true);playUiSound('accept');}catch {setCopied(false);playUiSound('error');}}
  return prepared ? <div className="inquiry-preview"><span className="eyebrow orange"><Check size={15} /> YOUR INQUIRY IS READY</span><h2>A good beginning.</h2><p>Review your message below. Open it in your email app to send it to the studio. Nothing has been sent yet.</p><pre>{draft}</pre><div className="form-actions"><a className="button orange-button" href={mailto}><Mail size={17} /> Open email app <ArrowUpRight size={17} /></a><button className="button outline-button" onClick={copy}>{copied ? <Check size={17} /> : <Copy size={17} />}{copied ? 'Copied' : 'Copy inquiry'}</button></div><button className="text-link" onClick={() => setPrepared(false)}><ArrowLeft size={16} /> Edit details</button></div> : <form className="contact-form" onSubmit={e => {e.preventDefault();setPrepared(true);playUiSound('accept');}}><div className="form-row"><label>Your name <span>*</span><input name="name" autoComplete="name" required placeholder="Alex Curious" maxLength={100} value={values.name} onChange={e => setValues({...values,name:e.target.value})} /></label><label>Email address <span>*</span><input name="email" type="email" autoComplete="email" required placeholder="alex@company.com" maxLength={200} value={values.email} onChange={e => setValues({...values,email:e.target.value})} /></label></div><label>Company <span className="optional">OPTIONAL</span><input name="company" autoComplete="organization" placeholder="A name we should know?" maxLength={150} value={values.company} onChange={e => setValues({...values,company:e.target.value})} /></label><fieldset><legend>What do you have in mind?</legend><div className="interest-options">{['A new website','Design & branding','Design & development','An app or custom software','AI & automation','Ongoing collaboration','Something else'].map(item => <label key={item}><input type="radio" name="interest" value={item} checked={interest===item} onChange={() => setInterest(item)} /><span>{item}</span></label>)}</div></fieldset><label>Budget range<select name="budget" value={budget} onChange={e => setBudget(e.target.value)}><option>Let’s discuss</option><option>Under $2,000</option><option>$2,000 – $5,000</option><option>$5,000 – $10,000</option><option>$10,000+</option></select></label><label>A little about your idea <span>*</span><textarea name="message" required minLength={10} maxLength={2500} rows={4} placeholder="The big idea, the small details, and what you want to make happen." value={values.message} onChange={e => setValues({...values,message:e.target.value})} /></label><div className="form-actions"><button className="button orange-button" type="submit" data-cursor="LET’S GO">Prepare inquiry <ArrowUpRight size={18} /></button><p>First draft: prepare a message,<br />then send it through your email app.</p></div></form>;
}
