'use client';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, ArrowUpRight, Search, Wifi, Folder, Grid2X2, List, Home, Sparkles, Box, NotebookPen, Mail, CalendarDays, Send, Monitor, ChevronRight, MessageCircle, Command, X, PanelLeft, Minus, Maximize2 } from 'lucide-react';
import { projects, services, resources, articles, socials } from '@/lib/content';
import { Symbol, ResourceCard, ArticleArt } from './ui';
import { ContactForm } from './contact-form';
import { SoundToggle } from './sound';

const apps = [
  {id:'work',label:'Projects',path:'/projects',icon:Folder,color:'blue'},
  {id:'services',label:'Expertise',path:'/services',icon:Sparkles,color:'orange'},
  {id:'tools',label:'Toolbox',path:'/tools-and-resources',icon:Box,color:'cream'},
  {id:'studio',label:'The studio',path:'/about',icon:Monitor,color:'peach'},
  {id:'journal',label:'Journal',path:'/blog',icon:NotebookPen,color:'yellow'},
  {id:'contact',label:'Mail',path:'/contact',icon:Mail,color:'blue'},
  {id:'assistant',label:'Assistant',path:'/assistant',icon:Sparkles,color:'orb'},
  {id:'calendar',label:'Calendar',path:'/calendar',icon:CalendarDays,color:'calendar'},
];
type StudioWindow={id:string;path:string;x:number;y:number;z:number;minimized:boolean;maximized:boolean};
type OpenApp=(path:string)=>void;
function appFor(path:string){return apps.find(a=>path===a.path||path.startsWith(a.path+'/'))||{id:'info',label:'Read me',path,icon:NotebookPen,color:'cream'};}
function createWindow(path:string,z:number,index=0):StudioWindow {return {id:appFor(path).id,path,x:index*24,y:index*20,z,minimized:false,maximized:false};}

export function DesktopShell(){
  const pathname=usePathname();const router=useRouter();
  const [windows,setWindows]=useState<StudioWindow[]>(()=>pathname==='/desktop'?[]:[createWindow(pathname,1)]);
  const topZ=useRef(2); const [clock,setClock]=useState(''); const [menu,setMenu]=useState('');
  const [spotlight,setSpotlight]=useState(false);const [query,setQuery]=useState('');const searchDialog=useRef<HTMLDialogElement>(null);
  const [sidebar,setSidebar]=useState(false);
  const active=[...windows].filter(w=>!w.minimized).sort((a,b)=>b.z-a.z)[0];
  const open:OpenApp=(path)=>{setWindows(current=>{const existing=current.find(w=>w.id===appFor(path).id);return existing?current.map(w=>w.id===existing.id?{...w,path,minimized:false,z:++topZ.current}:w):[...current,createWindow(path,++topZ.current,current.length%3)];});setMenu('');setSpotlight(false);setSidebar(false);if(path!==pathname)router.push(path);};
  useEffect(()=>{if(pathname==='/desktop')return;setWindows(current=>{const existing=current.find(w=>w.id===appFor(pathname).id);return existing?current.map(w=>w.id===existing.id?{...w,path:pathname,minimized:false,z:++topZ.current}:w):[...current,createWindow(pathname,++topZ.current,current.length%3)];});},[pathname]);
  useEffect(()=>{const update=()=>setClock(new Date().toLocaleString('en-US',{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}));update();const timer=setInterval(update,30000);const keys=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSpotlight(v=>!v);}if(e.key==='Escape'){setMenu('');setSpotlight(false);}};window.addEventListener('keydown',keys);return()=>{clearInterval(timer);window.removeEventListener('keydown',keys);};},[]);
  useEffect(()=>{if(spotlight){searchDialog.current?.showModal();setQuery('');}else searchDialog.current?.close();},[spotlight]);
  useEffect(()=>{const booking=()=>open('/calendar');window.addEventListener('high4tech:booking',booking);return()=>window.removeEventListener('high4tech:booking',booking);});
  function close(id:string){const remaining=windows.filter(w=>w.id!==id);setWindows(remaining);if(active?.id===id){const next=remaining.filter(w=>!w.minimized).sort((a,b)=>b.z-a.z)[0];router.replace(next?.path||'/desktop');}}
  function focus(w:StudioWindow){setWindows(current=>current.map(item=>item.id===w.id?{...item,z:++topZ.current}:item));}
  function minimize(id:string){setWindows(current=>current.map(w=>w.id===id?{...w,minimized:true}:w));}
  function zoom(id:string){setWindows(current=>current.map(w=>w.id===id?{...w,maximized:!w.maximized,z:++topZ.current}:w));}
  function showDesktop(){setWindows(current=>current.map(w=>({...w,minimized:true})));setMenu('');router.push('/desktop');}
  const results=[...apps.map(a=>({name:a.label,path:a.path,type:'Application'})),...projects.map(p=>({name:p.name,path:'/projects/'+p.slug,type:'Project'})),...articles.map(a=>({name:a.title,path:'/blog/'+a.slug,type:'Journal'}))].filter(r=>(r.name+' '+r.type).toLowerCase().includes(query.toLowerCase()));
  return <div className="studio-os">
    <div className="os-wallpaper" aria-hidden="true"><div className="wallpaper-fold one"/><div className="wallpaper-fold two"/><div className="wallpaper-type">h<span>4</span>t.</div><span className="wallpaper-credit">A LITTLE DIFFERENT BY DESIGN.</span></div>
    <header className="os-menubar"><Link href="/" className="os-system-mark" aria-label="High4Tech home">✳</Link><strong>High4Tech OS</strong><div className="os-menus">{['File','View','Help'].map(label=><div className="os-menu-wrap" key={label}><button aria-expanded={menu===label} onClick={()=>setMenu(menu===label?'':label)}>{label}</button>{menu===label&&<div className="os-menu-popover">{label==='File'?apps.slice(0,6).map(a=><button key={a.id} onClick={()=>open(a.path)}><a.icon size={14}/>{a.label}<ChevronRight size={12}/></button>):label==='View'?<><button onClick={showDesktop}>Show desktop</button><button onClick={()=>{setSpotlight(true);setMenu('');}}>Search the studio <span>⌘ K</span></button>{active&&<button onClick={()=>{zoom(active.id);setMenu('');}}>Toggle full window</button>}</>:<><button onClick={()=>open('/assistant')}>Ask the assistant</button><button onClick={()=>open('/contact')}>Contact the studio</button><a href={socials.whatsapp} target="_blank" rel="noopener noreferrer">WhatsApp <ArrowUpRight size={13}/></a></>}</div>}</div>)}</div><div className="os-menu-right"><SoundToggle/><button aria-label="Search the studio" onClick={()=>setSpotlight(true)}><Search size={14}/></button><Wifi size={15}/><time suppressHydrationWarning>{clock}</time><Link href="/" className="os-home">Home ↗</Link></div></header>
    {menu&&<button className="os-menu-dismiss" aria-label="Close menu" onClick={()=>setMenu('')}/>}
    <main id="main" className="os-desktop" aria-label="High4Tech desktop">
      <div className="desktop-welcome"><span className="os-widget-eyebrow">YOUR NEXT IDEA STARTS HERE.</span><h1>Make yourself<br/><i>at home.</i></h1><p>Open a folder. Follow your curiosity.</p><button onClick={()=>open('/assistant')} className="desktop-assistant-widget"><span className="assistant-orb"/><span><strong>A little help?</strong><small>Your studio companion is here.</small></span><ArrowUpRight size={18}/></button><div className="desktop-photo"><span>THE PEOPLE BEHIND THE PIXELS</span><img src="/brand/mascots.svg" alt="High4Tech studio mascots"/><i>Nice to meet you.</i></div></div>
      <div className="desktop-shortcuts">{[apps[0],apps[1],apps[2],apps[4],apps[3]].map(a=><button className="desktop-shortcut" key={a.id} onClick={()=>open(a.path)}><span className={`desktop-folder ${a.color}`}>{a.id==='studio'?<img src="/brand/mark.png" alt=""/>:<a.icon size={31} strokeWidth={1.3}/>}</span><span>{a.id==='studio'?'Read me':a.label}</span></button>)}</div>
      {windows.map(w=><AppWindow key={w.id} window={w} active={active?.id===w.id} sidebar={sidebar} setSidebar={setSidebar} onFocus={()=>focus(w)} onClose={()=>close(w.id)} onMinimize={()=>minimize(w.id)} onZoom={()=>zoom(w.id)} onMove={(x,y)=>setWindows(current=>current.map(item=>item.id===w.id?{...item,x,y}:item))} open={open}/>)}
      {!active&&<div className="desktop-hint"><Command size={13}/> K to find anything <span>or start with a folder →</span></div>}
    </main>
    <nav className="os-dock" aria-label="Studio dock"><Link className="dock-item" href="/" aria-label="Home — return to landing page"><span className="dock-icon home"><Home size={29}/></span><span className="dock-tooltip">Home</span></Link><div className="dock-divider"/>{apps.map(a=><button className={`dock-item ${active?.id===a.id?'dock-active':''}`} key={a.id} onClick={()=>open(windows.find(w=>w.id===a.id)?.path||a.path)} aria-label={`Open ${a.label}`} aria-pressed={active?.id===a.id}><span className={`dock-icon ${a.color}`}>{a.id==='assistant'?<span className="dock-orb"/>:a.id==='calendar'?<><small suppressHydrationWarning>{new Date().toLocaleDateString('en-US',{month:'short'}).toUpperCase()}</small><b suppressHydrationWarning>{new Date().getDate()}</b></>:a.id==='studio'?<img src="/brand/mark.png" alt=""/>:<a.icon size={30} strokeWidth={1.5}/>}</span><span className="dock-tooltip">{a.label}</span><i className={windows.some(w=>w.id===a.id)?'running':''}/></button>)}<div className="dock-divider"/><button className="dock-item" aria-label="Show desktop" onClick={showDesktop}><span className="dock-icon desktop"><Grid2X2 size={26}/></span><span className="dock-tooltip">Desktop</span></button></nav>
    <dialog className="os-spotlight" ref={searchDialog} onCancel={()=>setSpotlight(false)} onClick={e=>{if(e.target===searchDialog.current)setSpotlight(false);}}><form onSubmit={e=>{e.preventDefault();if(results[0])open(results[0].path);}}><Search size={22}/><input autoFocus aria-label="Search apps and projects" placeholder="Search the studio…" value={query} onChange={e=>setQuery(e.target.value)}/><button type="button" onClick={()=>setSpotlight(false)} aria-label="Close search"><X size={18}/></button></form><div className="spotlight-results">{results.length?results.map(r=><button key={r.path} onClick={()=>open(r.path)}><span>{r.name}</span><small>{r.type}</small><ArrowUpRight size={15}/></button>):<p>No matches. Try “Projects”, “Design”, or “Mail”.</p>}</div><footer><span>↑ Find your next idea</span><span>ESC to close</span></footer></dialog>
  </div>;
}

function AppWindow({window:w,active,sidebar,setSidebar,onFocus,onClose,onMinimize,onZoom,onMove,open}:{window:StudioWindow;active:boolean;sidebar:boolean;setSidebar:(v:boolean)=>void;onFocus:()=>void;onClose:()=>void;onMinimize:()=>void;onZoom:()=>void;onMove:(x:number,y:number)=>void;open:OpenApp}){
  const drag=useRef<{x:number;y:number;bx:number;by:number}|null>(null);const app=appFor(w.path);
  const [search,setSearch]=useState('');const [list,setList]=useState(false);
  useEffect(()=>setSearch(''),[w.path]);
  const compact=['assistant','calendar'].includes(w.id);
  const label=w.path.split('/').length>2?(projects.find(p=>w.path.endsWith(p.slug))?.name||services.find(s=>w.path.endsWith(s.slug))?.short||articles.find(a=>w.path.endsWith(a.slug))?.title||app.label):app.label;
  return <section className={`os-window ${active?'is-active':''} ${w.minimized?'is-minimized':''} ${w.maximized?'is-maximized':''} ${compact?'compact-window':''} app-${w.id} ${sidebar?'sidebar-open':''}`} style={{'--window-x':`${w.x}px`,'--window-y':`${w.y}px`,zIndex:w.z} as React.CSSProperties} aria-label={`${app.label} window`} onPointerDown={onFocus}>
    <header className="window-titlebar" onDoubleClick={e=>{if(!(e.target as HTMLElement).closest('button'))onZoom();}} onPointerDown={e=>{if((e.target as HTMLElement).closest('button')||w.maximized||window.innerWidth<=800)return;drag.current={x:e.clientX,y:e.clientY,bx:w.x,by:w.y};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!drag.current)return;onMove(Math.max(-window.innerWidth*.3,Math.min(window.innerWidth*.3,drag.current.bx+e.clientX-drag.current.x)),Math.max(-35,Math.min(window.innerHeight-180,drag.current.by+e.clientY-drag.current.y)));}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}>
      <div className="traffic-lights"><button className="close" aria-label={`Close ${app.label}`} onClick={onClose}><X size={9}/></button><button className="minimize" aria-label={`Minimize ${app.label}`} onClick={onMinimize}><Minus size={9}/></button><button className="maximize" aria-label={`Maximize ${app.label}`} onClick={onZoom}><Maximize2 size={8}/></button></div><span><app.icon size={13}/>{label}</span><button className="window-sidebar-toggle" aria-label="Toggle sidebar" onClick={()=>setSidebar(!sidebar)}><PanelLeft size={15}/></button>
    </header>
    <div className="window-layout">{!compact&&<aside className="finder-sidebar"><span className="sidebar-label">FAVORITES</span>{apps.filter(a=>!['calendar','assistant'].includes(a.id)).map(a=><button key={a.id} className={w.id===a.id?'selected':''} onClick={()=>open(a.path)}><a.icon size={16}/>{a.label}{a.id==='work'&&<small>2</small>}</button>)}<span className="sidebar-label second">STUDIO</span><button onClick={()=>open('/assistant')}><span className="sidebar-orb"/>Assistant</button><button onClick={()=>open('/calendar')}><CalendarDays size={16}/>Let’s talk</button><a href={socials.whatsapp} target="_blank" rel="noopener noreferrer"><MessageCircle size={16}/>WhatsApp<ArrowUpRight size={11}/></a><div className="sidebar-brand"><img src="/brand/wordmark.png" alt="High4Tech"/><span>INDEPENDENT CREATIVE STUDIO<br/>VERSION 02 · PREVIEW</span></div></aside>}
      <div className="window-main">{!compact&&<div className="finder-toolbar"><button aria-label="Back to folder" disabled={w.path===app.path} onClick={()=>open(app.path)}><ArrowLeft size={17}/></button><span className="finder-breadcrumb">High4Tech <ChevronRight size={12}/><strong>{app.label}</strong>{w.path!==app.path&&<><ChevronRight size={12}/><span>{label}</span></>}</span>{['work','tools','journal'].includes(w.id)&&w.path===app.path&&<><label className="finder-search"><Search size={13}/><input aria-label={`Search ${app.label}`} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search"/></label>{w.id==='work'&&<button aria-label={list?'Show grid view':'Show list view'} onClick={()=>setList(!list)}>{list?<Grid2X2 size={17}/>:<List size={17}/>}</button>}</>}</div>}
        <div className="window-scroll"><AppContent path={w.path} open={open} search={search} list={list}/></div>
        {!compact&&<footer className="window-status"><span><Folder size={11}/> High4Tech / {app.label.toLowerCase()}</span><span>{w.id==='work'?`${projects.length} projects`:'Made of ideas.'}</span></footer>}
      </div>
    </div>
  </section>;
}

function AppContent({path,open,search,list}:{path:string;open:OpenApp;search:string;list:boolean}){
  const [resourceFilter,setResourceFilter]=useState('All');
  if(path==='/assistant')return <Assistant open={open}/>;
  if(path==='/calendar')return <CalendarPreview open={open}/>;
  if(path.startsWith('/projects')){const project=projects.find(p=>path==='/projects/'+p.slug);return project?<article className="os-project-detail"><div className="project-detail-banner" style={{background:project.color}}><img src={project.image} alt={`${project.name} project`} /></div><div className="os-reading"><span className="os-kicker">SELECTED WORK / {project.year}</span><h1>{project.name}</h1><p className="os-lead">{project.description}</p><div className="project-specs"><div><small>DISCIPLINE</small>{project.type}</div><div><small>FORMAT</small>{project.category}</div></div><h2>A closer look.</h2><p>{project.intro}</p><p>Explore the visual direction and interface above. The full case study will follow as we bring more of the studio’s work into this space.</p><button className="os-button" onClick={()=>open('/contact')}>Have something in mind? <ArrowUpRight size={15}/></button><button className="os-text-button" onClick={()=>open('/projects')}>← Back to projects</button></div></article>:<div className="finder-content"><div className="os-page-heading"><div><span className="os-kicker">THE WORK FOLDER</span><h1>Good ideas. Out in the wild.</h1><p>A little of what we’ve been working on.</p></div><span className="os-count">02</span></div><div className={`project-folders ${list?'list-view':''}`}>{projects.filter(p=>(p.name+' '+p.category).toLowerCase().includes(search.toLowerCase())).map((p,i)=><button className="project-folder-card" key={p.slug} onClick={()=>open('/projects/'+p.slug)}><div className={`project-folder-art folder-${i}`}><span className="folder-tab"/><div className="folder-photo"><img src={p.image} alt=""/></div><div className="folder-front"><Folder size={23}/><span>H4T / PROJECT 0{i+1}</span></div></div><div className="project-folder-caption"><strong>{p.name}</strong><small>{p.type} · {p.year}</small><ArrowUpRight size={16}/></div></button>)}</div>{!projects.some(p=>(p.name+' '+p.category).toLowerCase().includes(search.toLowerCase()))&&<p className="os-empty">No projects match “{search}”.</p>}<div className="finder-note"><span>✳</span><p>Different challenges. The same curiosity.<br/><strong>Your next idea could be in this folder.</strong></p><button onClick={()=>open('/contact')}>Let’s talk <ArrowUpRight size={15}/></button></div></div>;}
  if(path.startsWith('/services')){const service=services.find(s=>path==='/services/'+s.slug);return service?<div className="os-reading service-note"><span className="os-kicker">CAPABILITY {service.number}</span><div className="service-note-art"><Symbol kind={service.symbol}/></div><h1>{service.title}</h1><p className="os-lead">{service.description}</p><div className="os-tags">{service.tags.map(t=><span key={t}>{t}</span>)}</div><h2>What we can bring.</h2><ul className="os-deliverables">{service.deliverables.map((d,i)=><li key={d}><span>0{i+1}</span>{d}</li>)}</ul>{service.draft&&<small className="os-preview-note">Service scope preview — to be confirmed with the studio.</small>}<button className="os-button" onClick={()=>open('/calendar')}>Let’s explore your idea <ArrowUpRight size={15}/></button></div>:<div className="finder-content"><div className="os-page-heading"><div><span className="os-kicker">WHAT WE BRING</span><h1>Different skills.<br/>One shared ambition.</h1><p>Strategy, design, and development in good company.</p></div></div><div className="os-services">{services.map(s=><button key={s.slug} onClick={()=>open('/services/'+s.slug)}><div><Symbol kind={s.symbol}/></div><span>{s.number} / CAPABILITY</span><h2>{s.short}<ArrowUpRight size={20}/></h2><p>{s.description}</p><small>{s.tags.join(' · ')}</small></button>)}</div></div>;}
  if(path==='/tools-and-resources'){const filtered=resources.filter(r=>(resourceFilter==='All'||r.price===resourceFilter)&&(r.title+' '+r.category).toLowerCase().includes(search.toLowerCase()));return <div className="finder-content"><div className="os-page-heading"><div><span className="os-kicker">THE STUDIO TOOLBOX</span><h1>A few useful things.</h1><p>Free resources and tools worth opening.</p></div></div><div className="os-filter" aria-label="Resource filters">{['All','Free','Paid'].map(f=><button aria-pressed={resourceFilter===f} className={resourceFilter===f?'selected':''} key={f} onClick={()=>setResourceFilter(f)}>{f}{f==='All'?' tools':''}</button>)}</div><div className="os-resource-grid">{filtered.map(r=><ResourceCard key={r.id} resource={r}/>)}</div>{!filtered.length&&<p className="os-empty">No tools match this search.</p>}<p className="os-preview-note">Tools open on their own platforms. Purchases, accounts, and support are handled there.</p></div>;}
  if(path==='/about')return <div className="os-about"><div className="os-about-portrait"><span>THE PEOPLE BEHIND THE PIXELS</span><img src="/brand/mascots.svg" alt="The illustrated High4Tech studio mascots"/><i>Good to meet you.</i></div><div className="os-reading"><span className="os-kicker">README / THE STUDIO</span><h1>Independent minds.<br/>Shared curiosity.</h1><p className="os-lead">We’re High4Tech. A creative technology studio turning ideas into identities, websites, and digital experiences.</p><p>We like thoughtful design, a good technical challenge, and work with a point of view. Our process brings design and development into the same conversation from the beginning.</p><div className="about-principles"><div><b>01</b><h3>Think clearly.</h3><p>Understand the people, the problem, and what a good result looks like.</p></div><div><b>02</b><h3>Make with intent.</h3><p>Give every interaction and visual decision a reason to be there.</p></div><div><b>03</b><h3>Stay curious.</h3><p>Keep asking better questions. There’s always another possibility.</p></div></div><button className="os-button" onClick={()=>open('/contact')}>Let’s make something move <ArrowUpRight size={15}/></button></div></div>;
  if(path.startsWith('/blog')){const article=articles.find(a=>path==='/blog/'+a.slug);return article?<article className="os-reading os-article"><span className="os-kicker">{article.category.toUpperCase()} / {article.read.toUpperCase()}</span><h1>{article.title}</h1><p className="os-lead">{article.summary}</p><ArticleArt kind={article.artwork}/>{article.paragraphs.map(p=><p key={p}>{p}</p>)}<button className="os-text-button" onClick={()=>open('/blog')}>← All studio notes</button></article>:<div className="finder-content"><div className="os-page-heading"><div><span className="os-kicker">THOUGHTS IN PROGRESS</span><h1>The studio journal.</h1><p>Notes on design, technology, and making things matter.</p></div></div><div className="os-journal-list">{articles.filter(a=>(a.title+' '+a.category).toLowerCase().includes(search.toLowerCase())).map(a=><button key={a.slug} onClick={()=>open('/blog/'+a.slug)}><ArticleArt kind={a.artwork}/><div><span className="os-kicker">{a.category} · {a.read}</span><h2>{a.title}</h2><p>{a.summary}</p><span className="os-text-button">Open note <ArrowUpRight size={14}/></span></div></button>)}</div>{!articles.some(a=>(a.title+' '+a.category).toLowerCase().includes(search.toLowerCase()))&&<p className="os-empty">No notes match “{search}”.</p>}</div>;}
  if(path==='/contact')return <div className="os-mail"><div className="mail-envelope"><span>New message</span><span>To: <strong>High4Tech Studio</strong> &lt;sales@high4tech.io&gt;</span></div><div className="os-reading"><span className="os-kicker">A GOOD PLACE TO START</span><h1>What’s on your mind?</h1><p className="os-lead">A project, a question, or a good idea. We’re all ears.</p><ContactForm/></div></div>;
  if(path==='/privacy'||path==='/terms')return <div className="os-reading"><span className="os-kicker">STUDIO NOTES / PREVIEW</span><h1>{path==='/privacy'?'Your privacy.':'A few ground rules.'}</h1><p>This is a frontend design preview. Inquiry forms prepare a local draft; messages are not submitted to a server. The assistant uses local scripted responses and does not connect to an AI service.</p><p>External tools, social links, email, and WhatsApp open their respective services, whose own terms and privacy policies apply. No purchases or account creation take place on this website.</p><p>Final legal policies will be added before the public launch once the site’s services and integrations are finalized.</p><button className="os-button" onClick={()=>open('/contact')}>Contact the studio <ArrowUpRight size={15}/></button></div>;
  return <div className="os-reading"><h1>This folder is empty.</h1><p>That page could not be found.</p><Link href="/" className="os-button">Back to home <ArrowUpRight size={16}/></Link></div>;
}

function Assistant({open}:{open:OpenApp}){
  const [messages,setMessages]=useState<{role:string;text:string;link?:string;label?:string}[]>([]);const [input,setInput]=useState('');const history=useRef<HTMLDivElement>(null);
  useEffect(()=>{history.current?.scrollTo({top:history.current.scrollHeight,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});},[messages]);
  function ask(value:string){const text=value.trim();if(!text)return;let answer={role:'assistant',text:'We bring design and technology together: identities, websites, apps, and custom digital experiences. Want to take a look at our capabilities?',link:'/services',label:'Explore expertise'};if(/work|project|portfolio/i.test(text))answer={role:'assistant',text:'The work folder is a good place to start. Take a look at The Shipping Kite and Driver Finder — two projects from the High4Tech portfolio.',link:'/projects',label:'Open work folder'};else if(/tool|resource|buy|free|paid/i.test(text))answer={role:'assistant',text:'The toolbox brings free resources and studio tools together. Each opens on its own platform, where you can use it or make a purchase.',link:'/tools-and-resources',label:'Open the toolbox'};else if(/call|contact|book|cost|price|hello|start|timeline/i.test(text))answer={role:'assistant',text:'Tell the studio what you have in mind. Scope shapes timing and cost, so a conversation is the best first step. You can prepare an inquiry in Mail.',link:'/contact',label:'Write to the studio'};setMessages(m=>[...m,{role:'user',text},answer]);setInput('');}
  return <div className="os-assistant"><div className="assistant-conversation" ref={history}><div className={`assistant-intro ${messages.length?'has-messages':''}`}><span className="assistant-orb large"/><span className="os-kicker">YOUR CURIOUS COMPANION</span><h1>A little help?<br/>A little inspiration?</h1><p>Find your way around our world.<br/>What would you like to explore?</p></div>{messages.length===0&&<div className="assistant-prompts">{['What do you do?','Show me your work','Explore the toolbox','Start a conversation'].map(q=><button key={q} onClick={()=>ask(q)}>{q}<ArrowUpRight size={13}/></button>)}</div>}<div className="os-messages" role="log" aria-live="polite">{messages.map((m,i)=><div key={i} className={`os-message ${m.role}`}><small>{m.role==='user'?'YOU':'HIGH4TECH ASSISTANT'}</small><p>{m.text}</p>{m.link&&<button onClick={()=>open(m.link!)}>{m.label}<ArrowUpRight size={13}/></button>}</div>)}</div></div><form className="assistant-compose" onSubmit={e=>{e.preventDefault();ask(input);}}><input value={input} onChange={e=>setInput(e.target.value)} aria-label="Ask the assistant" placeholder="A question, a thought, an idea…" maxLength={500}/><button aria-label="Send to assistant" disabled={!input.trim()}><ArrowRight size={18}/></button></form><div className="assistant-disclaimer">FRONTEND PREVIEW · SCRIPTED STUDIO GUIDE</div></div>;
}

function CalendarPreview({open}:{open:OpenApp}){const [date,setDate]=useState('');const [topic,setTopic]=useState('A new website');return <div className="calendar-preview"><CalendarDays size={35} strokeWidth={1.2}/><span className="os-kicker">A FIRST CONVERSATION</span><h1>Big ideas.<br/>Small beginnings.</h1><p>A little time to talk about what you have in mind and where we could take it.</p><label>What’s on your mind?<select value={topic} onChange={e=>setTopic(e.target.value)}><option>A new website</option><option>Design & branding</option><option>An app or custom software</option><option>Something else</option></select></label><label>A date you have in mind<input type="date" value={date} onChange={e=>setDate(e.target.value)} min={new Date().toLocaleDateString('en-CA')}/></label><div className="calendar-note"><span>CALENDAR PREVIEW</span><p>{date?`Your preference: ${date}. `:''}Live availability will be added here. No meeting has been scheduled.</p></div><button className="os-button" onClick={()=>{sessionStorage.setItem('h4t-call-preference',JSON.stringify({topic,date}));open('/contact');}}>Prepare a call request <ArrowUpRight size={15}/></button></div>;}
