import { TrashIcon } from '@phosphor-icons/react/dist/ssr/Trash';
import { ArrowBendUpLeftIcon } from '@phosphor-icons/react/dist/ssr/ArrowBendUpLeft';
import { ArrowClockwiseIcon } from '@phosphor-icons/react/dist/ssr/ArrowClockwise';
import { ArrowCounterClockwiseIcon } from '@phosphor-icons/react/dist/ssr/ArrowCounterClockwise';
import { ArrowDownIcon } from '@phosphor-icons/react/dist/ssr/ArrowDown';
import { ArrowLeftIcon } from '@phosphor-icons/react/dist/ssr/ArrowLeft';
import { ArrowRightIcon } from '@phosphor-icons/react/dist/ssr/ArrowRight';
import { ArrowUpIcon } from '@phosphor-icons/react/dist/ssr/ArrowUp';
import { ArrowUpRightIcon } from '@phosphor-icons/react/dist/ssr/ArrowUpRight';
import { ArrowsOutSimpleIcon } from '@phosphor-icons/react/dist/ssr/ArrowsOutSimple';
import { BookOpenTextIcon } from '@phosphor-icons/react/dist/ssr/BookOpenText';
import { BrainIcon } from '@phosphor-icons/react/dist/ssr/Brain';
import { CalendarDotsIcon } from '@phosphor-icons/react/dist/ssr/CalendarDots';
import { CaretLeftIcon } from '@phosphor-icons/react/dist/ssr/CaretLeft';
import { CaretRightIcon } from '@phosphor-icons/react/dist/ssr/CaretRight';
import { ChatCircleDotsIcon } from '@phosphor-icons/react/dist/ssr/ChatCircleDots';
import { CheckIcon } from '@phosphor-icons/react/dist/ssr/Check';
import { ChecksIcon } from '@phosphor-icons/react/dist/ssr/Checks';
import { ClockIcon } from '@phosphor-icons/react/dist/ssr/Clock';
import { CodeIcon } from '@phosphor-icons/react/dist/ssr/Code';
import { CommandIcon } from '@phosphor-icons/react/dist/ssr/Command';
import { CopyIcon } from '@phosphor-icons/react/dist/ssr/Copy';
import { CubeIcon } from '@phosphor-icons/react/dist/ssr/Cube';
import { CurrencyDollarIcon } from '@phosphor-icons/react/dist/ssr/CurrencyDollar';
import { DatabaseIcon } from '@phosphor-icons/react/dist/ssr/Database';
import { DesktopIcon } from '@phosphor-icons/react/dist/ssr/Desktop';
import { EnvelopeSimpleIcon } from '@phosphor-icons/react/dist/ssr/EnvelopeSimple';
import { FileTextIcon } from '@phosphor-icons/react/dist/ssr/FileText';
import { FlowArrowIcon } from '@phosphor-icons/react/dist/ssr/FlowArrow';
import { FolderOpenIcon } from '@phosphor-icons/react/dist/ssr/FolderOpen';
import { FolderSimpleIcon } from '@phosphor-icons/react/dist/ssr/FolderSimple';
import { GameControllerIcon } from '@phosphor-icons/react/dist/ssr/GameController';
import { GlobeHemisphereWestIcon } from '@phosphor-icons/react/dist/ssr/GlobeHemisphereWest';
import { HouseSimpleIcon } from '@phosphor-icons/react/dist/ssr/HouseSimple';
import { ListIcon } from '@phosphor-icons/react/dist/ssr/List';
import { LockKeyIcon } from '@phosphor-icons/react/dist/ssr/LockKey';
import { MagnifyingGlassIcon } from '@phosphor-icons/react/dist/ssr/MagnifyingGlass';
import { MinusIcon } from '@phosphor-icons/react/dist/ssr/Minus';
import { MoonStarsIcon } from '@phosphor-icons/react/dist/ssr/MoonStars';
import { MusicNotesIcon } from '@phosphor-icons/react/dist/ssr/MusicNotes';
import { NewspaperClippingIcon } from '@phosphor-icons/react/dist/ssr/NewspaperClipping';
import { NotePencilIcon } from '@phosphor-icons/react/dist/ssr/NotePencil';
import { PaletteIcon } from '@phosphor-icons/react/dist/ssr/Palette';
import { PaperPlaneTiltIcon } from '@phosphor-icons/react/dist/ssr/PaperPlaneTilt';
import { PauseIcon } from '@phosphor-icons/react/dist/ssr/Pause';
import { PlayIcon } from '@phosphor-icons/react/dist/ssr/Play';
import { PlusIcon } from '@phosphor-icons/react/dist/ssr/Plus';
import { RobotIcon } from '@phosphor-icons/react/dist/ssr/Robot';
import { ScanIcon } from '@phosphor-icons/react/dist/ssr/Scan';
import { ShieldCheckIcon } from '@phosphor-icons/react/dist/ssr/ShieldCheck';
import { SidebarSimpleIcon } from '@phosphor-icons/react/dist/ssr/SidebarSimple';
import { SkipForwardIcon } from '@phosphor-icons/react/dist/ssr/SkipForward';
import { SparkleIcon } from '@phosphor-icons/react/dist/ssr/Sparkle';
import { SpeakerHighIcon } from '@phosphor-icons/react/dist/ssr/SpeakerHigh';
import { SpeakerSlashIcon } from '@phosphor-icons/react/dist/ssr/SpeakerSlash';
import { SquaresFourIcon } from '@phosphor-icons/react/dist/ssr/SquaresFour';
import { SunDimIcon } from '@phosphor-icons/react/dist/ssr/SunDim';
import { TrayIcon } from '@phosphor-icons/react/dist/ssr/Tray';
import { TrendUpIcon } from '@phosphor-icons/react/dist/ssr/TrendUp';
import { UserCircleIcon } from '@phosphor-icons/react/dist/ssr/UserCircle';
import { WifiHighIcon } from '@phosphor-icons/react/dist/ssr/WifiHigh';
import { XIcon } from '@phosphor-icons/react/dist/ssr/X';

import type { Icon, IconProps, IconWeight } from '@phosphor-icons/react';

// Direct SSR imports avoid loading the whole catalogue or requiring a context.
function glyph(Source: Icon, name: string, defaultWeight: IconWeight) {
  function Glyph({ size = 24, className = '', strokeWidth: _strokeWidth, weight = defaultWeight, ...props }: IconProps) {
    return <Source {...props} size={size} weight={weight}
      className={`h4t-icon ${className}`} data-icon={name} data-icon-weight={weight}
      aria-hidden={props['aria-label'] || props.alt ? undefined : true} />;
  }
  Glyph.displayName = `H4T${name}`;
  return Glyph;
}

export const ArrowDown = glyph(ArrowDownIcon, 'ArrowDown', 'regular');
export const ArrowLeft = glyph(ArrowLeftIcon, 'ArrowLeft', 'regular');
export const ArrowRight = glyph(ArrowRightIcon, 'ArrowRight', 'regular');
export const ArrowUp = glyph(ArrowUpIcon, 'ArrowUp', 'bold');
export const ArrowUpRight = glyph(ArrowUpRightIcon, 'ArrowUpRight', 'regular');
export const BookOpen = glyph(BookOpenTextIcon, 'BookOpenText', 'duotone');
export const Bot = glyph(RobotIcon, 'Robot', 'duotone');
export const Box = glyph(CubeIcon, 'Cube', 'duotone');
export const BrainCircuit = glyph(BrainIcon, 'Brain', 'duotone');
export const CalendarDays = glyph(CalendarDotsIcon, 'CalendarDots', 'duotone');
export const Check = glyph(CheckIcon, 'Check', 'bold');
export const CheckCheck = glyph(ChecksIcon, 'Checks', 'regular');
export const ChevronLeft = glyph(CaretLeftIcon, 'CaretLeft', 'regular');
export const ChevronRight = glyph(CaretRightIcon, 'CaretRight', 'regular');
export const Clock3 = glyph(ClockIcon, 'Clock', 'duotone');
export const Code2 = glyph(CodeIcon, 'Code', 'duotone');
export const Command = glyph(CommandIcon, 'Command', 'regular');
export const Copy = glyph(CopyIcon, 'Copy', 'duotone');
export const Database = glyph(DatabaseIcon, 'Database', 'duotone');
export const DollarSign = glyph(CurrencyDollarIcon, 'CurrencyDollar', 'regular');
export const FileText = glyph(FileTextIcon, 'FileText', 'duotone');
export const Folder = glyph(FolderSimpleIcon, 'FolderSimple', 'duotone');
export const FolderOpen = glyph(FolderOpenIcon, 'FolderOpen', 'duotone');
export const Gamepad2 = glyph(GameControllerIcon, 'GameController', 'duotone');
export const Globe2 = glyph(GlobeHemisphereWestIcon, 'GlobeHemisphereWest', 'duotone');
export const Grid2X2 = glyph(SquaresFourIcon, 'SquaresFour', 'duotone');
export const Home = glyph(HouseSimpleIcon, 'HouseSimple', 'duotone');
export const Inbox = glyph(TrayIcon, 'Tray', 'duotone');
export const List = glyph(ListIcon, 'List', 'regular');
export const LockKeyhole = glyph(LockKeyIcon, 'LockKey', 'duotone');
export const Mail = glyph(EnvelopeSimpleIcon, 'EnvelopeSimple', 'duotone');
export const Maximize2 = glyph(ArrowsOutSimpleIcon, 'ArrowsOutSimple', 'bold');
export const Menu = glyph(ListIcon, 'List', 'regular');
export const MessageCircle = glyph(ChatCircleDotsIcon, 'ChatCircleDots', 'duotone');
export const Minus = glyph(MinusIcon, 'Minus', 'bold');
export const Monitor = glyph(DesktopIcon, 'Desktop', 'duotone');
export const Moon = glyph(MoonStarsIcon, 'MoonStars', 'duotone');
export const Music2 = glyph(MusicNotesIcon, 'MusicNotes', 'duotone');
export const NotebookPen = glyph(NewspaperClippingIcon, 'NewspaperClipping', 'duotone');
export const Palette = glyph(PaletteIcon, 'Palette', 'duotone');
export const PanelLeft = glyph(SidebarSimpleIcon, 'SidebarSimple', 'regular');
export const Pause = glyph(PauseIcon, 'Pause', 'fill');
export const PenSquare = glyph(NotePencilIcon, 'NotePencil', 'duotone');
export const Play = glyph(PlayIcon, 'Play', 'fill');
export const Plus = glyph(PlusIcon, 'Plus', 'regular');
export const Reply = glyph(ArrowBendUpLeftIcon, 'ArrowBendUpLeft', 'regular');
export const RotateCcw = glyph(ArrowCounterClockwiseIcon, 'ArrowCounterClockwise', 'regular');
export const RotateCw = glyph(ArrowClockwiseIcon, 'ArrowClockwise', 'regular');
export const Scan = glyph(ScanIcon, 'Scan', 'duotone');
export const Search = glyph(MagnifyingGlassIcon, 'MagnifyingGlass', 'regular');
export const Send = glyph(PaperPlaneTiltIcon, 'PaperPlaneTilt', 'duotone');
export const ShieldCheck = glyph(ShieldCheckIcon, 'ShieldCheck', 'duotone');
export const SkipForward = glyph(SkipForwardIcon, 'SkipForward', 'fill');
export const Sparkles = glyph(SparkleIcon, 'Sparkle', 'duotone');
export const SquarePen = glyph(NotePencilIcon, 'NotePencil', 'duotone');
export const Sun = glyph(SunDimIcon, 'SunDim', 'duotone');
export const TrendingUp = glyph(TrendUpIcon, 'TrendUp', 'duotone');
export const UserRound = glyph(UserCircleIcon, 'UserCircle', 'duotone');
export const Volume2 = glyph(SpeakerHighIcon, 'SpeakerHigh', 'duotone');
export const VolumeX = glyph(SpeakerSlashIcon, 'SpeakerSlash', 'duotone');
export const Wifi = glyph(WifiHighIcon, 'WifiHigh', 'regular');
export const Workflow = glyph(FlowArrowIcon, 'FlowArrow', 'duotone');
export const X = glyph(XIcon, 'X', 'bold');

export const Trash2 = glyph(TrashIcon, 'Trash', 'duotone');
