'use client';
import { useDesktopStorage } from './desktop-storage';
import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, ArrowUpRight } from './icons';
import { useStudioContent } from './content-provider';
export function NewsroomStack({open}:{open:(path:string)=>void}){
 const {articles:allArticles}=useStudioContent();const {trashed}=useDesktopStorage();const articles=allArticles.filter(a=>!trashed.some(f=>f.id==='blog-'+a.slug));const [index,setIndex]=useState(0),[offset,setOffset]=useState(0);const deck=useRef<HTMLDivElement>(null),origin=useRef<number|null>(null),dragged=useRef(false);const count=articles.length;
 function move(direction:number){if(count)setIndex(i=>(i+direction+count)%count);setOffset(0);}
 const current=count?index%count:0;
 useEffect(()=>{if(deck.current?.contains(document.activeElement))deck.current.querySelector<HTMLButtonElement>('[data-depth="0"]')?.focus({preventScroll:true});},[current]);
 return <section className="news-ticket-stack" aria-label="Newsroom card stack"><div className="news-ticket-header"><span className="live-panel-label">NEWSROOM</span><div><button aria-label="Previous newsroom card" disabled={count<2} onClick={()=>move(-1)}><ArrowLeft size={13}/></button><button aria-label="Next newsroom card" disabled={count<2} onClick={()=>move(1)}><ArrowRight size={13}/></button></div></div><div ref={deck} className="news-ticket-deck" onPointerDown={e=>{if(e.button!==0||count<2)return;origin.current=e.clientX;dragged.current=false;e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(origin.current===null)return;const dx=e.clientX-origin.current;if(Math.abs(dx)>8)dragged.current=true;setOffset(Math.max(-150,Math.min(150,dx)));}} onPointerUp={e=>{if(origin.current===null)return;const dx=e.clientX-origin.current;origin.current=null;if(Math.abs(dx)>45)move(dx<0?1:-1);else setOffset(0);}} onPointerCancel={()=>{origin.current=null;setOffset(0);}} onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();move(e.key==='ArrowLeft'?-1:1);}}}>
 {count?[...Array(Math.min(3,count))].map((_,depth)=>{const article=articles[(current+depth)%count];return <button className="news-ticket" key={article.slug} data-depth={depth} aria-hidden={depth>0} tabIndex={depth? -1:0} style={{zIndex:3-depth,transform:depth?`translateY(${depth*6}px) scale(${1-depth*.035})`:`translateX(${offset}px) rotate(${offset/25}deg)`}} onClick={()=>{if(dragged.current){dragged.current=false;return;}open('/newsroom/'+article.slug);}}><span>{article.category}<ArrowUpRight size={13}/></span><strong>{article.title}</strong><small>{article.read}<i/>Studio perspectives</small></button>;}):<button className="news-ticket" onClick={()=>open('/newsroom')}><strong>Explore the Newsroom.</strong></button>}
 </div><div className="news-ticket-footer"><span className="news-ticket-dots" aria-hidden="true">{articles.map((a,i)=><i key={a.slug} className={i===current?'is-current':''}/>)}</span><span role="status" aria-live="polite">{count?current+1:0} / {count}</span></div></section>;
}
