import Link from 'next/link';
import type { StudioContent } from '@/lib/studio-content';
import { StudioVideos } from './studio-videos';
import { ArrowUpRight, ArrowLeft, Plus } from '@/components/icons';
import { Hero } from './hero';
import { LandingV2 } from './landing-v2';
import { BookingButton } from './site-shell';
import { ProjectGallery, ResourceCatalog, JournalGallery } from './catalog';
import { ContactForm } from './contact-form';
import { SectionHeading, ProjectCard, ServiceRows, Symbol, ResourceCard, ArticleCard, FAQ, ContactCTA, Process, PageIntro, ArticleArt } from './ui';
import { projects, services, articles, resources, socials } from '@/lib/content';

export function HomePage() {
  return <LandingV2 />;
}
export function OriginalHomePage() {
  return <><Hero /><div className="capability-strip"><div className="wrap"><span>DESIGN THAT CONNECTS</span><span className="orange">✳</span><span>CODE THAT DELIVERS</span><span className="orange">✳</span><span>A LITTLE DIFFERENT BY DESIGN</span><span className="orange">✳</span></div></div>
    <section id="selected-work" className="wrap section-space selected-work"><SectionHeading number="01" title="Work that speaks." note="SELECTED PROJECTS" href="/projects" link="All selected work" /><div className="project-grid">{projects.map((p,i) => <ProjectCard project={p} index={i} key={p.slug} />)}</div></section>
    <section className="wrap services-section section-space"><SectionHeading number="02" title="Different skills. One ambition." note="WHAT WE BRING" href="/services" link="Explore services" /><ServiceRows /></section>
    <section className="studio-section wrap section-space"><div className="studio-copy" data-reveal><span className="eyebrow"><span className="orange">03 /</span> THE PEOPLE BEHIND THE PIXELS</span><h2>A LITTLE<br /><span className="orange">HIGHER.</span><br />A LITTLE<br />DIFFERENT.</h2><p>We’re High4Tech. A creative technology studio where curious minds turn ideas into distinctive digital experiences.</p><Link className="text-link" href="/about" data-cursor="MEET US">Get to know the studio <ArrowUpRight size={18} /></Link></div><div className="mascot-stage" data-cursor="HEY YOU" data-reveal><span className="mascot-label micro-label">SERIOUS ABOUT THE WORK.<br />LESS SERIOUS ABOUT OURSELVES.</span><div className="mascot-orbit" /><img src="/brand/mascots.svg" width="1536" height="1024" alt="High4Tech’s two illustrated studio mascots" loading="lazy" /><span className="mascot-note">Good company.<br /><i>Great possibilities.</i></span><Plus className="mascot-plus" size={24} /></div></section>
    <section className="wrap section-space process-section"><SectionHeading number="04" title="From what if, to what’s next." note="HOW WE GET THERE" /><Process /></section>
    <section className="resource-section section-space"><div className="wrap"><SectionHeading number="05" title="Good tools. Great possibilities." note="TOOLS & RESOURCES" href="/tools-and-resources" link="Open the toolbox" /><div className="resource-grid">{resources.slice(0,3).map(r => <ResourceCard resource={r} key={r.id} />)}</div></div></section>
    <section className="wrap section-space"><SectionHeading number="06" title="Notes from curious minds." note="THE JOURNAL" href="/blog" link="All studio notes" /><div className="article-grid">{articles.map(a => <ArticleCard article={a} key={a.slug} />)}</div></section><FAQ /><ContactCTA /></>;
}
export function ServicesPage() {
  return <><PageIntro index="02" eyebrow="OUR CAPABILITIES" title={<>GOOD IDEAS.<br /><span className="orange">GREAT CRAFT.</span></>} description="The creative thinking and technical skills to take your next idea somewhere interesting."><BookingButton className="text-link">Find the right starting point</BookingButton></PageIntro><section className="wrap"><ServiceRows /></section><section className="wrap section-space"><SectionHeading number="01" title="Built together, from the beginning." note="OUR APPROACH" /><Process /></section><FAQ /><ContactCTA /></>;
}
export function ServiceDetail({ service }: { service: StudioContent['services'][number] }) {
  return <><section className="detail-hero wrap"><Link className="back-link" href="/services"><ArrowLeft size={15} /> ALL SERVICES</Link><div className="service-detail-intro"><div><span className="eyebrow orange">CAPABILITY / {service.number}</span><h1>{service.title.split(' ').slice(0,-1).join(' ')}<br /><span className="orange">{service.title.split(' ').at(-1)}</span></h1><p>{service.description}</p><div className="service-tags">{service.tags.map(tag => <span key={tag}>{tag}</span>)}</div><BookingButton /></div><div className="service-detail-art"><Symbol kind={service.symbol} /><span className="micro-label">GOOD THINKING. BETTER MAKING.</span></div></div></section><div className="wrap"><StudioVideos videos={service.videos}/></div><section className="wrap section-space deliverables"><div><span className="eyebrow orange">WHAT WE CAN BUILD TOGETHER</span><h2>More than<br />a good idea.</h2><p>Every project starts with its own questions. These are some of the ways we can help shape the answers.</p>{service.draft && <p className="preview-note">Service outline for review. The final digital growth offering will be confirmed with the studio.</p>}</div><ol>{service.deliverables.map((d,i) => <li key={d}><span>0{i+1}</span>{d}<Plus size={18} /></li>)}</ol></section><section className="wrap section-space"><SectionHeading number="01" title="An idea in action." note="SELECTED WORK" href="/projects" link="Explore our work" /><div className="project-grid">{projects.map((p,i) => <ProjectCard project={p} index={i} key={p.slug} />)}</div></section><FAQ /><ContactCTA /></>;
}
export function ProjectsPage() {
  return <><PageIntro index="01" eyebrow="SELECTED WORK" title={<>LESS TALK.<br /><span className="orange">MORE MAKING.</span></>} description="A selection of interfaces, identities, and digital experiences from the High4Tech portfolio." /><section className="wrap gallery-section"><ProjectGallery /></section><ContactCTA /></>;
}
export function ProjectDetail({ project }: { project: StudioContent['projects'][number] }) {
  const next = projects.find(p => p.slug !== project.slug)!;
  return <><section className="project-detail-heading wrap"><Link className="back-link" href="/projects"><ArrowLeft size={15} /> SELECTED WORK</Link><div className="case-heading"><div><span className="eyebrow orange">{project.category} / {project.year}</span><h1>{project.name}<span className="orange">.</span></h1></div><p>{project.description}</p></div><div className="case-tags"><span className="tag">{project.type}</span><span className="micro-label muted">HIGH4TECH / CASE STUDY</span></div></section><div className="case-cover wrap"><img src={project.image} width="1024" height="755" alt={`${project.name} portfolio presentation`} /></div><section className="case-story wrap section-space"><span className="eyebrow orange">THE PROJECT</span><div><h2>A closer look<br />at the experience.</h2><p>{project.intro}</p><StudioVideos videos={project.videos}/><p>{project.slug === 'the-shipping-kite' ? 'A deep blue palette, expansive imagery, and bright orange accents give the presentation a distinctive visual rhythm. The layouts bring the story of cargo transportation into focus.' : 'A high-contrast yellow and black palette sets a confident tone. The portfolio presentation brings together mobile screens, interface details, and the identity behind the experience.'}</p><a className="text-link" href={project.source} target="_blank" rel="noopener noreferrer">View original portfolio entry <ArrowUpRight size={17} /></a><p className="preview-note">Project imagery from our existing portfolio. The full client story and confirmed outcomes will be added before launch.</p></div></section><section className="wrap section-space next-project"><SectionHeading number="↗" title="Keep exploring." note="NEXT PROJECT" /><ProjectCard project={next} index={projects.indexOf(next)} /></section><ContactCTA /></>;
}
export function ResourcesPage() {
  return <><PageIntro index="03" eyebrow="TOOLS & RESOURCES" title={<>YOUR NEXT<br /><span className="orange">UNFAIR ADVANTAGE.</span></>} description="A few useful things for curious people. Explore free resources and discover tools on the platforms where they live." /><section className="wrap catalog-section"><ResourceCatalog /></section><ContactCTA /></>;
}
export function AboutPage() {
  return <><PageIntro index="04" eyebrow="THE STUDIO" title={<>CURIOUS MINDS.<br /><span className="orange">SHARED AMBITION.</span></>} description="We bring creative thinking and technical precision into the same room. Then we see where the idea takes us." /><section className="about-mascots wrap"><span className="eyebrow">THE CHARACTERS BEHIND THE CHARACTER</span><img src="/brand/mascots.svg" alt="The High4Tech studio mascots" width="1536" height="1024" /><span className="about-caption">A little personality goes a long way<span className="orange">.</span></span></section><section className="wrap section-space studio-manifesto"><span className="eyebrow orange">WHAT WE BELIEVE</span><div><h2>Good work comes<br />from good curiosity.</h2><p>High4Tech connects design and development to make digital experiences with character. We care about how something looks, how it works, and how it makes people feel.</p><p>We like the early questions, the unexpected direction, and the details that make an idea feel like yours. The best work brings them all together.</p></div></section><section className="wrap section-space"><SectionHeading number="01" title="A few things we stand for." note="OUR APPROACH" /><div className="values-grid">{[['Think openly.','Make room for different perspectives. Ask the question that changes the direction.'],['Make thoughtfully.','Build with purpose, from the first sketch to the smallest interaction.'],['Stay human.','Clear conversations. Useful experiences. Work that understands the people it’s for.']].map(([title,text],i) => <article key={title}><span className="orange micro-label">0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section><ContactCTA /></>;
}
export function JournalPage() {
  return <><PageIntro index="05" eyebrow="THE JOURNAL" title={<>A FEW<br /><span className="orange">BRIGHT IDEAS.</span></>} description="Thoughts on design, technology, and the interesting space between them. Notes from the studio, shared with you." /><section className="wrap gallery-section"><JournalGallery /></section><div className="social-note wrap"><span className="eyebrow">MORE FROM THE STUDIO</span><h2>The conversation<br />keeps going.</h2><a className="text-link" href={socials.instagram} target="_blank" rel="noopener noreferrer">Follow on Instagram <ArrowUpRight size={18} /></a></div><ContactCTA /></>;
}
export function ArticlePage({ article }: { article: typeof articles[number] }) {
  return <><section className="article-heading wrap"><Link className="back-link" href="/blog"><ArrowLeft size={15} /> THE JOURNAL</Link><div className="article-meta"><span className="orange">{article.category}</span><span>{article.read} / EDITORIAL PREVIEW</span></div><h1>{article.title}</h1><p>{article.summary}</p></section><div className="article-cover wrap"><ArticleArt kind={article.artwork} /></div><article className="article-body"><span className="eyebrow">A NOTE FROM HIGH4TECH</span>{article.paragraphs.map((p,i) => <p key={i}>{p}</p>)}<div className="article-end"><span className="orange">✳</span><Link className="text-link" href="/blog">Back to the journal <ArrowUpRight size={17} /></Link></div></article><section className="wrap section-space"><SectionHeading number="↗" title="Another good thought." note="KEEP READING" /><div className="article-grid">{articles.filter(a => a.slug!==article.slug).map(a => <ArticleCard article={a} key={a.slug} />)}</div></section><ContactCTA /></>;
}
export function ContactPage() {
  return <><PageIntro index="06" eyebrow="LET’S TALK" title={<>IT STARTS<br />WITH <span className="orange">HELLO.</span></>} description="A big idea, a small question, or something that hasn’t quite taken shape yet. We’d love to hear it." /><section className="contact-layout wrap"><aside className="contact-aside"><span className="eyebrow orange">DIRECT TO THE STUDIO</span><a className="contact-email" href="mailto:high4tech360@gmail.com">high4tech360@gmail.com <ArrowUpRight size={21} /></a><p>Prefer a quick conversation?</p><a className="text-link" href={socials.whatsapp} target="_blank" rel="noopener noreferrer">Say hi on WhatsApp <ArrowUpRight size={17} /></a><div className="contact-call"><span className="eyebrow">LET’S FIND THE RIGHT DIRECTION.</span><BookingButton className="text-link" /></div><img className="contact-mascots" src="/brand/mascots.svg" alt="Our illustrated studio mascots" width="400" height="267" /></aside><ContactForm /></section></>;
}
export function PolicyPage({ type }: { type: 'privacy' | 'terms' }) {
  return <><PageIntro index="INFO" eyebrow="A LITTLE CLARITY" title={type === 'privacy' ? <>YOUR <span className="orange">PRIVACY.</span></> : <>SITE <span className="orange">TERMS.</span></>} description="This first draft is a preview. The final policy will be prepared around the services and integrations used at launch." /><article className="policy-copy wrap"><h2>{type === 'privacy' ? 'About this preview' : 'Using the draft'}</h2><p>{type === 'privacy' ? 'The inquiry form lets you review a draft, send it to the support inbox, or open your email app. Assistant questions are sent to our server to search published studio knowledge, without an external AI provider. When studio support is connected, conversations are stored for team follow-up using a private browser cookie. Name, phone number, and email are required before starting chat. These self-reported contact details and recent history are cached on this browser. A private cookie resumes the chat; email alone does not recover history on another browser. Preview conversations are not stored in the CMS. Links to tools, WhatsApp, and social platforms take you to services with their own privacy policies.' : 'This website demonstrates the proposed High4Tech experience. Some catalog items and editorial content are examples for review. Tool use and purchases happen on their respective external platforms.'}</p><p>Questions? Contact <a href="mailto:high4tech360@gmail.com">high4tech360@gmail.com</a>.</p><Link href="/" className="text-link">Back to the studio <ArrowUpRight size={17} /></Link></article></>;
}
