'use client';
import { useRef, useState } from 'react';
import { ArrowRight, ArrowUpRight, Check, Code2, BrainCircuit, Monitor } from './icons';
import { buildCategories, buildExtras, calculateBuild, complexityLevels, supportPlans, type BuildCategory } from '@/lib/pricing-calculator';
export const usd = (n: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n);
export function PricingCalculator({ open }: { open: (path: string) => void }) {
  const [category, setCategory] = useState<BuildCategory>('web'), [platform, setPlatform] = useState('wordpress'), [units, setUnits] = useState(5), [complexity, setComplexity] = useState('essential'), [extras, setExtras] = useState<string[]>([]), [support, setSupport] = useState('care');
  const estimate = calculateBuild({ category, platform, units, complexity, extras, support });
  const receipt = useRef<HTMLElement>(null);
  function changeCategory(id: BuildCategory) { const next = buildCategories.find(c => c.id === id)!; setCategory(id); setPlatform(next.platforms[0].id); setUnits(next.platforms[0].included); setExtras([]); }
  function share() {
    const breakdown = [`Sample estimate: ${estimate.category.label} / ${estimate.platform.label}`, `${estimate.units} ${estimate.platform.unit}, ${estimate.complexity.label} scope`, `Add-ons: ${estimate.extras.map(e => e.label).join(', ') || 'None'}`, `Build: ${usd(estimate.total)}; ${estimate.support.label}: ${usd(estimate.support.price)}/month`, 'Illustrative USD estimate; final scope and quote to be confirmed.'].join('\n');
    sessionStorage.setItem('h4t-estimate-brief', breakdown);
    sessionStorage.setItem('h4t-call-preference', JSON.stringify({ topic: category === 'ai' ? 'AI & automation' : category === 'app' ? 'An app or custom software' : 'A new website', date: '' }));
    open('/contact');
  }
  return <div className="inner-page estimate-page">
    <header className="estimate-heading"><div><span className="inner-label">PRICING / PLAN YOUR BUILD</span><h1>Make room<br/>for your next idea<span>.</span></h1><p>Choose the platform. Shape the scope.<br/>See where your budget starts.</p></div><span className="estimate-preview">Sample USD rates<br/><small>For planning, not a binding quote.</small></span></header>
    <div className="estimate-mobile-total"><span>Build estimate<strong aria-live="polite">{usd(estimate.total)}</strong></span><small>+ {usd(estimate.support.price)}/month<br/>selected support</small><button onClick={() => receipt.current?.scrollIntoView({ behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth', block: 'start' })}>Breakdown <ArrowRight size={14}/></button></div>
    <nav className="estimate-categories" aria-label="Project category">{buildCategories.map((c, i) => { const Icon = [Monitor, Code2, BrainCircuit][i]; return <button key={c.id} aria-pressed={category === c.id} onClick={() => changeCategory(c.id)}><Icon size={25}/><span><strong>{c.label}</strong><small>{c.description}</small></span><ArrowUpRight size={18}/></button>; })}</nav>
    <div className="estimate-layout"><div className="estimate-config">
      <section><div className="estimate-step"><span>01</span><h2>Your platform</h2></div><div className="estimate-platforms" role="group" aria-label="Platform">{estimate.category.platforms.map(p => <button key={p.id} aria-pressed={platform === p.id} onClick={() => { setPlatform(p.id); setUnits(p.included); }}><strong>{p.label}</strong><small>From {usd(p.base)}</small></button>)}</div><p className="estimate-included">Includes discovery, design, implementation, testing and handover.</p></section>
      <section><div className="estimate-step"><span>02</span><h2>Shape the scope</h2></div><label className="estimate-range">How many {estimate.platform.unit}?<output>{estimate.units}</output><input aria-label={`Number of ${estimate.platform.unit}`} type="range" min={estimate.platform.included} max={30} value={estimate.units} onChange={e => setUnits(Number(e.target.value))}/><small>{estimate.platform.included} included · {usd(estimate.platform.extra)} for each additional {estimate.platform.unit === 'pages' ? 'page' : 'unit'}</small></label><div className="estimate-complexity" role="group" aria-label="Project complexity">{complexityLevels.map(c => <button key={c.id} aria-pressed={complexity === c.id} onClick={() => setComplexity(c.id)}><strong>{c.label}</strong><small>{c.text}</small><span>{c.factor === 1 ? 'Base scope' : `+${Math.round((c.factor - 1) * 100)}%`}</span></button>)}</div></section>
      <section><div className="estimate-step"><span>03</span><h2>A few useful additions</h2></div><div className="estimate-addons">{buildExtras.filter(e => (e.categories as readonly string[]).includes(category)).map(e => <label key={e.id}><input type="checkbox" checked={extras.includes(e.id)} onChange={() => setExtras(current => current.includes(e.id) ? current.filter(x => x !== e.id) : [...current, e.id])}/><span>{e.label}</span><strong>+{usd(e.cost)}</strong></label>)}</div></section>
      <section><div className="estimate-step"><span>04</span><h2>Support after launch</h2></div><div className="estimate-support" role="group" aria-label="Monthly support">{supportPlans.map(p => <button key={p.id} aria-pressed={support === p.id} onClick={() => setSupport(p.id)}><span><strong>{p.label}</strong><b>{usd(p.price)}<small>/mo</small></b></span><ul>{p.items.map(item => <li key={item}><Check size={12}/>{item}</li>)}</ul></button>)}</div><p className="estimate-included">Monthly support is optional. Included hours reset each month; extra work is scoped separately.</p></section>
    </div><aside ref={receipt} className="estimate-receipt"><div><span className="inner-label">YOUR PROJECT OUTLINE</span><span className="receipt-symbol">✳</span></div><h2>{estimate.platform.label}</h2><p>{estimate.complexity.label} · {estimate.units} {estimate.platform.unit}</p><dl><dt>Platform & initial scope</dt><dd>{usd(estimate.platform.base)}</dd><dt>Additional scope</dt><dd>{usd(estimate.scope)}</dd><dt>Complexity adjustment</dt><dd>{usd(estimate.complexityCost)}</dd>{estimate.extras.map(e => <div key={e.id}><dt>{e.label}</dt><dd>{usd(e.cost)}</dd></div>)}</dl><div className="receipt-total" aria-live="polite" aria-atomic="true"><span>One-time build estimate</span><strong>{usd(estimate.total)}</strong><div><span>{estimate.support.label} support</span><b>{usd(estimate.support.price)}<small>/month</small></b></div><p>First-year planning total <b>{usd(estimate.firstYear)}</b><small>Build + 12 months of selected support</small></p></div><button className="premium-action" onClick={share}>Discuss this estimate <ArrowUpRight size={17}/></button><small>Sample rates. Hosting, domains, third-party licenses, AI usage and taxes are excluded. Final deliverables and price are agreed before work begins.</small></aside></div>
    <footer className="estimate-footer"><h2>Have a scope already?</h2><p>Share your brief and we’ll put together a proposal around it.</p><button className="inner-link" onClick={() => open('/contact')}>Talk to the studio <ArrowRight size={16}/></button></footer>
  </div>;
}
