'use client';
import { useState } from 'react';
import { ArrowLeft, ArrowUpRight, Search } from '@/components/icons';
import { useStudioContent } from './content-provider';
import { resourcePlatforms, platformsOf, type StudioResource } from '@/lib/resource-platforms';
import { ResourceCard, Symbol } from './ui';
import { StudioVideos } from './studio-videos';
export function ResourceBrowser({ open, search = '' }: { open?: (path: string) => void; search?: string }) {
  const { resources } = useStudioContent(), [platform, setPlatform] = useState('all'), [price, setPrice] = useState('All'), [query, setQuery] = useState('');
  const filtered = resources.filter(r => (platform === 'all' || platformsOf(r.platforms).includes(platform as never)) && (price === 'All' || r.price === price) && `${r.title} ${r.description} ${r.category} ${r.capabilities || ''}`.toLowerCase().includes((search || query).toLowerCase().trim()));
  return <div className="resource-browser"><div className="platform-tabs" aria-label="Tool platforms">{[{ value: 'all', label: 'All platforms' }, ...resourcePlatforms].map(p => <button key={p.value} aria-pressed={platform === p.value} onClick={() => setPlatform(p.value)}>{p.label}<small>{resources.filter(r => p.value === 'all' || platformsOf(r.platforms).includes(p.value as never)).length}</small></button>)}</div><div className="resource-browser-controls"><div className="os-filter" aria-label="Tool prices">{['All', 'Free', 'Paid'].map(p => <button key={p} aria-pressed={price === p} className={price === p ? 'selected' : ''} onClick={() => setPrice(p)}>{p}</button>)}</div>{search ? <span className="resource-external-search">Matching “{search}”</span> : <label className="search-field"><Search size={16}/><input aria-label="Search tools by purpose" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search by name or purpose"/></label>}</div><p className="resource-result-count">{filtered.length} {filtered.length === 1 ? 'resource' : 'resources'}</p><div className="os-resource-grid">{filtered.map(resource => <ResourceCard key={resource.id} resource={resource} open={open}/>)}</div>{!filtered.length && <div className="resource-empty"><Search size={27}/><h2>Nothing published here yet.</h2><p>Try another platform or ask the studio about the tool you need.</p><button className="os-button" onClick={() => { setPlatform('all'); setPrice('All'); setQuery(''); }}>{search ? 'Clear platform filters' : 'Show all resources'}</button></div>}<p className="os-preview-note">Use and purchase tools on their own platforms. Availability follows the studio’s published catalog.</p></div>;
}
export function ResourceDetail({ resource, open }: { resource: StudioResource; open?: (path: string) => void }) {
  return <article className="os-reading resource-detail"><button className="os-text-button" onClick={() => open ? open('/tools-and-resources') : location.assign('/tools-and-resources')}><ArrowLeft size={15}/> App Store</button><div className={`resource-detail-art art-${resource.icon}`}><Symbol kind={resource.icon}/></div><span className="os-kicker">{resource.category} / {resource.price}</span><h1>{resource.title}</h1><div className="os-tags">{platformsOf(resource.platforms).map(p => <span key={p}>{resourcePlatforms.find(option => option.value === p)?.label}</span>)}</div><p className="os-lead">{resource.description}</p>{resource.capabilities && <><h2>What it helps with</h2><p>{resource.capabilities}</p></>}<StudioVideos videos={resource.videos}/>{resource.url ? <a className="os-button" href={resource.url} target="_blank" rel="noopener noreferrer">{resource.price === 'Paid' ? 'View on the seller’s platform' : 'Open resource'}<ArrowUpRight size={16}/></a> : <p className="os-preview-note">This tool is a preview. Its platform link will be added by the studio.</p>}</article>;
}
