'use client';
import { ArrowUpRight, ChevronRight, Code2, Palette, TrendingUp, Globe2, Check, MessageCircle } from 'lucide-react';
import { projects, services, resources, articles, faqs } from '@/lib/content';
import { Symbol } from './ui';

export function StudioHome({open}:{open:(path:string)=>void}){
  return <div className="studio-home-content">
    <header className="home-profile"><div className="home-profile-icon"><Palette size={32}/></div><div><h1>High4Tech Studio</h1></div><span className="home-availability"><i/>Available for ideas</span></header>
    <section className="home-intro"><span>DESIGN × TECHNOLOGY</span><h2>Make the digital<br/><em>feel alive.</em></h2><p>We turn ideas into identities, websites, and digital experiences. Thoughtful design. Useful technology. A little personality.</p><button className="os-button" onClick={()=>open('/contact')}>Start a conversation <ArrowUpRight size={16}/></button><div className="home-orbit" aria-hidden="true"><Symbol kind="orbit"/></div></section>
    <div className="home-section-title"><h2>Services & expertise</h2><span>From idea to launch</span></div>
    <section className="settings-group">{services.map((s,i)=>{const Icon=[Palette,Code2,TrendingUp][i];return <button key={s.slug} className="settings-row" onClick={()=>open('/services/'+s.slug)}><span className={`settings-icon icon-${i}`}><Icon size={20}/></span><span><strong>{s.short}</strong><small>{s.tags.join(' · ')}</small></span><ChevronRight size={17}/></button>;})}</section>
    <section className="home-quick-apps"><button onClick={()=>open('/ai-zone')}><span>✳</span><strong>AI Zone</strong><small>Automation, thoughtfully applied.</small><ChevronRight size={16}/></button><button onClick={()=>open('/pricing')}><span>$</span><strong>Ways to work together</strong><small>Explore sample packages.</small><ChevronRight size={16}/></button></section>
    <div className="home-section-title"><h2>Inside the studio</h2><button onClick={()=>open('/about')}>Meet us <ChevronRight size={13}/></button></div>
    <section className="home-bento"><div className="home-bento-stats"><div><strong>{services.length}</strong><span>Connected disciplines</span></div><div><strong>{projects.length}</strong><span>Selected projects</span></div><div><strong>01</strong><span>Shared ambition</span></div></div><div className="home-bento-object"><Symbol kind="flower"/><span>Design with character.</span></div><div className="home-bento-world"><Globe2 size={150} strokeWidth={.55}/><span className="home-availability"><i/>Available worldwide</span><h3>Good work.<br/>No borders.</h3></div><div className="home-bento-people"><img src="/brand/mascots-cutout.svg" alt="Our two High4Tech mascots"/><div><span>THE PEOPLE BEHIND THE PIXELS</span><h3>Serious about the work.<br/>Curious about everything.</h3><p>We bring design and development into the same conversation, from the first question to the final detail.</p><button onClick={()=>open('/about')}>A little about us <ArrowUpRight size={14}/></button></div></div></section>
    <div className="home-section-title"><h2>Selected work</h2><button onClick={()=>open('/projects')}>Open Finder <ChevronRight size={13}/></button></div>
    <section className="home-projects">{projects.map(p=><button key={p.slug} onClick={()=>open('/projects/'+p.slug)}><img src={p.image} alt={p.name}/><span><strong>{p.name}</strong><ArrowUpRight size={16}/></span><small>{p.type}</small></button>)}</section>
    <div className="home-section-title"><h2>How we work</h2><span>Clear from the start</span></div>
    <section className="settings-group">{[['Discover','Your idea, audience, and ambition.'],['Define','A clear plan and visual direction.'],['Create','Design and development, together.'],['Launch','Refine the details. Prepare for what’s next.']].map(([title,description],i)=><div className="settings-row" key={title}><span className="process-index">0{i+1}</span><span><strong>{title}</strong><small>{description}</small></span><Check size={16}/></div>)}</section>
    <div className="home-section-title"><h2>Tools & resources</h2><button onClick={()=>open('/tools-and-resources')}>View all <ChevronRight size={13}/></button></div>
    <section className="settings-group">{resources.slice(0,3).map(r=><button className="settings-row" key={r.id} onClick={()=>open('/tools-and-resources')}><span className="settings-icon icon-1"><Code2 size={19}/></span><span><strong>{r.title}</strong><small>{r.category}</small></span><span className="home-tag">{r.price}</span><ChevronRight size={15}/></button>)}</section>
    <div className="home-section-title"><h2>Newsroom</h2></div><section className="settings-group">{articles.map(a=><button className="settings-row" key={a.slug} onClick={()=>open('/newsroom/'+a.slug)}><span><strong>{a.title}</strong><small>{a.category} · {a.read}</small></span><ChevronRight size={16}/></button>)}</section>
    <div className="home-section-title"><h2>A little clarity</h2></div><section className="settings-group home-faq">{faqs.map(f=><details key={f.question}><summary>{f.question}<ChevronRight size={15}/></summary><p>{f.answer}</p></details>)}</section>
    <footer className="home-end"><MessageCircle size={25}/><h2>Got something in mind?</h2><p>Let’s see where the idea takes us.</p><button className="os-button" onClick={()=>open('/contact')}>Say hello <ArrowUpRight size={16}/></button></footer>
  </div>;
}
