'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowRight, ChevronLeft, X, Play, Pause, Music2, SkipForward, Volume2 } from 'lucide-react';
import { projects } from '@/lib/content';
import { BrandIcon } from './studio-sections';
import { FeatureTips } from './feature-tips';
import { playUiSound } from './sound';
import { studioStack } from './studio-apps';

export function MascotFace({second=false}:{second?:boolean}){return <span className={`mascot-face ${second?'second':''}`}><svg viewBox={second?'780 55 730 920':'35 55 730 920'} aria-hidden="true"><image href="/brand/mascots-cutout.svg" width="1536" height="1024"/></svg></span>;}

export function StudioIntro(){
  const [boot,setBoot]=useState(true);
  useEffect(()=>{const timer=setTimeout(()=>setBoot(false),1600);return()=>clearTimeout(timer);},[]);
  return <>{boot&&<div className="studio-boot" role="status" aria-label="Opening High4Tech Studio"><img src="/brand/mark.png" alt="High4Tech"/><div className="boot-progress"><i/></div><span>Make yourself at home.</span></div>}<FeatureTips/></>;
}

export function DesktopCompanion(){
  const face=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(!matchMedia('(pointer: fine) and (prefers-reduced-motion: no-preference)').matches)return;const move=(e:PointerEvent)=>{const el=face.current;if(!el)return;const hidden=!!(e.target as HTMLElement).closest('.os-window,.os-dock,.os-menubar,dialog,button,a,input,.studio-live-panel');el.style.opacity=hidden?'0':'1';el.style.transform=`translate3d(${Math.min(e.clientX+22,innerWidth-64)}px,${Math.min(e.clientY+20,innerHeight-65)}px,0)`;};const hide=()=>{if(face.current)face.current.style.opacity='0';};document.addEventListener('pointermove',move);document.addEventListener('pointerleave',hide);return()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerleave',hide);};},[]);
  return <div ref={face} className="desktop-companion" aria-hidden="true"><MascotFace second/></div>;
}

export function DesktopLoops({kind}:{kind:'tools'|'clients'}){
  return <div className={`desktop-loop ${kind}-loop`} aria-label={kind==='tools'?'Studio tools':'Selected clients'}><div className="loop-mask"><div className="loop-track">{[0,1,2,3].map(n=><div key={n} aria-hidden={n>0}>{kind==='tools'?studioStack.map(tool=><span key={tool.icon}><img src={tool.icon==='figma'?'/icons/figma/figma.svg':`/icons/${tool.icon}.svg`} alt=""/>{tool.name}<i>✦</i></span>):projects.map(p=><span key={p.slug}>{p.name}<i>✦</i></span>)}</div>)}</div></div></div>;
}

// Original ambient compositions generated locally. No audio files or account credentials required.
const tracks=[{name:'Soft Focus',notes:[130.81,164.81,196,246.94]},{name:'After Hours',notes:[110,130.81,164.81,220]},{name:'First Light',notes:[146.83,185,220,277.18]}];
export function StudioMusic(){
  const [playing,setPlaying]=useState(false),[track,setTrack]=useState(0),[expanded,setExpanded]=useState(false),[provider,setProvider]=useState('Library'),[url,setUrl]=useState(''),[embed,setEmbed]=useState(''),[error,setError]=useState(''),[volume,setVolume]=useState(.18);
  const ctx=useRef<AudioContext|null>(null),master=useRef<GainNode|null>(null),timer=useRef<ReturnType<typeof setInterval>|null>(null),playingRef=useRef(false),trackRef=useRef(0),volumeRef=useRef(.18);
  function stop(){if(timer.current)clearInterval(timer.current);timer.current=null;void ctx.current?.close();ctx.current=null;master.current=null;playingRef.current=false;setPlaying(false);}
  async function start(index=trackRef.current){if(ctx.current)stop();try{const audio=new AudioContext();ctx.current=audio;await audio.resume();if(ctx.current!==audio)return;const out=audio.createGain();out.gain.value=volumeRef.current;out.connect(audio.destination);master.current=out;let beat=0;const schedule=()=>{const now=audio.currentTime;tracks[index].notes.forEach((f,i)=>{const osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.frequency.value=f;gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(.07,now+1.3+i*.1);gain.gain.exponentialRampToValueAtTime(.0001,now+7);osc.connect(gain);gain.connect(out);osc.start(now);osc.stop(now+7.1);});const bell=audio.createOscillator(),g=audio.createGain();bell.frequency.value=tracks[index].notes[beat++%4]*4;g.gain.setValueAtTime(.035,now);g.gain.exponentialRampToValueAtTime(.0001,now+3);bell.connect(g);g.connect(out);bell.start();bell.stop(now+3.1);};schedule();timer.current=setInterval(schedule,6000);playingRef.current=true;setPlaying(true);}catch{setError('Audio couldn’t start. Try pressing play again.');}}
  useEffect(()=>()=>{if(timer.current)clearInterval(timer.current);void ctx.current?.close();},[]);
  function selectTrack(i:number,play=true){trackRef.current=i;setTrack(i);setEmbed('');setProvider('Library');if(play||playingRef.current)void start(i);}
  function connect(){try{const parsed=new URL(url);let src='';if(provider==='Spotify'&&parsed.hostname==='open.spotify.com'&&/^\/(track|playlist|album)\/[a-zA-Z0-9]+\/?$/.test(parsed.pathname))src=`https://open.spotify.com/embed${parsed.pathname}`;if(provider==='Apple Music'&&parsed.hostname==='music.apple.com'&&/^\/[a-z]{2}\/(album|playlist|song)\//.test(parsed.pathname))src=`https://embed.music.apple.com${parsed.pathname}${parsed.search}`;if(!src)throw Error();stop();setEmbed(src);setError('');playUiSound('accept');}catch{playUiSound('error');setError(`Paste a valid ${provider} album, song, or playlist link.`);}}
  return <section className={`studio-music ${playing?'is-playing':''}`} aria-label="Studio music" data-tip="music"><div className="music-heading"><span>HIGH4TECH FM</span><button aria-label={expanded?'Close music library':'Open music library'} onClick={()=>setExpanded(!expanded)}><Music2 size={16}/></button></div><div className="music-now"><div className="music-cover"><i/><i/><i/><i/></div><div><strong>{embed?provider:tracks[track].name}</strong><small>{embed?'Your selection':playing?'Studio ambient · Playing':'Studio ambient'}</small></div><button aria-label={playing?'Pause music':'Play music'} onClick={()=>{setEmbed('');playing?stop():void start();}}>{playing?<Pause size={16}/>:<Play size={16}/>}</button><button aria-label="Next track" onClick={()=>selectTrack((track+1)%tracks.length,false)}><SkipForward size={15}/></button></div><button className="music-library-link" onClick={()=>setExpanded(!expanded)}>Library & your music <ArrowRight size={12}/></button>{expanded&&<div className="music-expanded"><div className="music-tabs">{['Library','Spotify','Apple Music'].map(p=><button key={p} aria-pressed={provider===p} onClick={()=>{setProvider(p);setError('');setEmbed('');}}>{p==='Spotify'?<BrandIcon name="spotify"/>:p==='Apple Music'?<BrandIcon name="applemusic"/>:null}{p}</button>)}</div>{provider==='Library'?<>{tracks.map((t,i)=><button className="music-track" key={t.name} onClick={()=>track===i&&playing?stop():selectTrack(i)}><Music2 size={14}/><span>{t.name}</span>{track===i&&playing?<Pause size={12}/>:<Play size={12}/>}</button>)}<label className="music-volume"><Volume2 size={15}/><input type="range" aria-label="Music volume" min="0" max=".5" step=".01" value={volume} onChange={e=>{const value=Number(e.target.value);setVolume(value);volumeRef.current=value;if(master.current&&ctx.current)master.current.gain.setTargetAtTime(value,ctx.current.currentTime,.1);}}/></label></>:<><label className="music-link-label">Play your own selection<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder={provider==='Spotify'?'https://open.spotify.com/playlist/…':'https://music.apple.com/…'}/></label><button className="os-button" onClick={connect}>Load player <ArrowRight size={13}/></button><p>Paste a shared music link. Listening and sign-in are handled by {provider}.</p>{error&&<p role="alert">{error}</p>}</>}</div>}{embed&&<iframe title={`${provider} music player`} src={embed} height="175" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"/>}</section>;
}
