export const services = [
  { slug: 'design', number: '01', title: 'Design with character.', short: 'Design', description: 'Distinctive identities and digital experiences. Built around your people, your purpose, and what comes next.', tags: ['UI / UX design', 'Visual identity', 'Design systems'], deliverables: ['Discovery and visual direction', 'User journeys and wireframes', 'High-fidelity interface design', 'Interactive prototypes', 'A cohesive design system'], symbol: 'flower' },
  { slug: 'development', number: '02', title: 'Built to move forward.', short: 'Development', description: 'Custom websites, apps, and software that turn good ideas into something people can actually use.', tags: ['Web development', 'Applications', 'Custom software'], deliverables: ['Technical discovery', 'Responsive frontend development', 'Interactive experiences', 'Accessibility and performance review', 'Launch preparation and handover'], symbol: 'orbit' },
  { slug: 'digital-growth', number: '03', title: 'Make your next move.', short: 'Digital growth', description: 'A considered approach to your digital presence, from the first impression to the next conversation.', tags: ['Digital strategy', 'SEO', 'Marketing'], deliverables: ['Digital presence review', 'Audience and conversion journeys', 'Content and SEO priorities', 'Campaign direction', 'Measurement recommendations'], symbol: 'spark', draft: true },
];

export const projects = [
  { slug: 'the-shipping-kite', name: 'The Shipping Kite', type: 'Web design & development', category: 'Websites', year: '2024', image: '/projects/shipping-kite.avif', color: '#06242d', description: 'A digital presence for a new perspective on ocean transportation.', source: 'https://high4tech.framer.ai/projects/silverlynx-technologies', intro: 'A project from the High4Tech portfolio, bringing together website design and development for the cargo and shipping space.' },
  { slug: 'driver-finder', name: 'Driver Finder', type: 'App design & development', category: 'Applications', year: '2024', image: '/projects/driver-finder.webp', color: '#ead100', description: 'A mobile experience for the people who keep things moving.', source: 'https://high4tech.framer.ai/projects/evergreen-solutions', intro: 'An app design and development project from the High4Tech portfolio. A closer look at the interfaces and visual direction.' },
];

import type { StudioResource } from './resource-platforms';
export const resources: StudioResource[] = [
  { id: 'shadergradient', title: 'ShaderGradient', description: 'Explore moving gradients and make your next interface a little less ordinary.', category: 'Design', price: 'Free', url: 'https://www.shadergradient.co/', icon: 'gradient', platforms: ['custom'], label: 'Community resource' },
  { id: 'liquid-logo', title: 'Liquid Logo', description: 'Turn a static mark into a flowing, liquid-metal experiment.', category: 'Design', price: 'Free', url: 'https://collidingscopes.github.io/liquid-logo/', icon: 'liquid', platforms: ['custom'], label: 'Community resource' },
  { id: 'react-three-fiber', title: 'React Three Fiber', description: 'A starting point for building interactive 3D experiences with React.', category: 'Development', price: 'Free', url: 'https://github.com/pmndrs/react-three-fiber', icon: 'cube', platforms: ['custom'], label: 'Community resource' },
  { id: 'studio-tool', title: 'The next studio tool.', description: 'A space for our paid tools. Purchases will happen on each tool’s own platform.', category: 'Studio tools', price: 'Paid', url: null, icon: 'tool', platforms: ['custom'], label: 'Catalog preview' },
];

export const articles = [
  { slug: 'beyond-the-first-impression', number: '01', title: 'Good design goes beyond the first impression.', category: 'Design', read: '3 min read', artwork: 'type', summary: 'A memorable opening matters. What happens after it matters just as much.', paragraphs: ['A great first screen can make someone pause. A great experience gives them a reason to stay. Those are connected jobs, but they are not the same job.', 'We think about a website as a sequence of useful moments: an introduction, an answer, a piece of work, a next step. Every visual decision should support one of those moments.', 'Strong typography, clear hierarchy, and thoughtful spacing give an interface character without making it harder to use. They also help a brand stay recognizable across screens.', 'The question is not how much we can fit into a page. It is how clearly the page can help someone understand what comes next.'] },
  { slug: 'motion-with-a-purpose', number: '02', title: 'A little motion. A lot of intention.', category: 'Development', read: '3 min read', artwork: 'orbit', summary: 'Making an interface feel alive without getting in the way.', paragraphs: ['Motion can connect a click to a result, show where something came from, or draw attention to a useful next step. It earns its place when it makes the experience easier to follow.', 'Decorative motion has a place too. A playful object can express a brand’s personality. The important part is keeping that personality from competing with the content.', 'We prefer a few deliberate interactions over an interface where every element is moving at once. A quiet page makes its memorable moments stand out.', 'Touch, keyboard, reduced-motion preferences, and older devices deserve the same care as the desktop experience. The website should still work when the animation is turned off.'] },
  { slug: 'from-idea-to-interface', number: '03', title: 'From a good idea to a useful interface.', category: 'Studio', read: '3 min read', artwork: 'grid', summary: 'Why the early questions shape the work that comes later.', paragraphs: ['A brief can describe a feature, a visual direction, or a problem. Before we move to a layout, we want to understand the people behind it and what they need to do.', 'That understanding becomes a journey. What does someone need to know first? Where might they hesitate? What should the next step feel like?', 'Wireframes and prototypes let those questions become something concrete. They make it easier to discuss the work before investing in the finished interface.', 'The result should connect the idea, the experience, and the implementation. Design and development work best when they keep talking to each other.'] },
];

export const faqs = [
  { question: 'What can we create together?', answer: 'Websites, digital identities, app interfaces, and custom digital experiences. Start with the idea or problem you have in mind, and we can work out the right shape for it.' },
  { question: 'Can you work with our existing brand?', answer: 'Yes. Existing guidelines can be the starting point. We can carry your identity into a new digital experience while keeping the details consistent.' },
  { question: 'Where do I buy a tool?', answer: 'Every tool links to its own platform. You will use that platform for pricing, purchases, accounts, and support.' },
  { question: 'How do we get started?', answer: 'Tell us a little about your project through the contact page, or reach out on WhatsApp. We can then discuss the scope and the next steps.' },
];

export const socials = { instagram: 'https://instagram.com/high_4_tech/', linkedin: 'https://linkedin.com/company/high4tech/', behance: 'https://behance.net/high4tech', whatsapp: 'https://wa.me/923256138361' };
